package com.whjbsoft.www.po;

import java.util.HashSet;
import java.util.Set;


/**
 * Bjxx generated by MyEclipse - Hibernate Tools
 */

public class Bjxx  implements java.io.Serializable {


    // Fields    

     private Integer bjzj;
     private String bjbh;
     private String bjmc;
     private String bzxx;
     private Integer bhzdz;
     private Set jsbjs = new HashSet(0);
     private Set xsxxes = new HashSet(0);
     private Set ggxxes = new HashSet(0);
     private String xxmc;
     private Set ksszs = new HashSet(0);

    // Constructors

  


	public Set getKsszs() {
		return ksszs;
	}


	public void setKsszs(Set ksszs) {
		this.ksszs = ksszs;
	}


	/** default constructor */
    public Bjxx() {
    }

    
    /** full constructor */
    public Bjxx(String bjbh, String bjmc, String bzxx, Integer bhzdz, Set jsbjs, Set xsxxes, Set ggxxes) {
        this.bjbh = bjbh;
        this.bjmc = bjmc;
        this.bzxx = bzxx;
        this.bhzdz = bhzdz;
        this.jsbjs = jsbjs;
        this.xsxxes = xsxxes;
        this.ggxxes = ggxxes;
    }

   
    // Property accessors

    public Integer getBjzj() {
        return this.bjzj;
    }
    
    public void setBjzj(Integer bjzj) {
        this.bjzj = bjzj;
    }

    public String getBjbh() {
        return this.bjbh;
    }
    
    public void setBjbh(String bjbh) {
        this.bjbh = bjbh;
    }

    public String getBjmc() {
        return this.bjmc;
    }
    
    public void setBjmc(String bjmc) {
        this.bjmc = bjmc;
    }

    public String getBzxx() {
        return this.bzxx;
    }
    
    public void setBzxx(String bzxx) {
        this.bzxx = bzxx;
    }

    public Integer getBhzdz() {
        return this.bhzdz;
    }
    
    public void setBhzdz(Integer bhzdz) {
        this.bhzdz = bhzdz;
    }

    public Set getJsbjs() {
        return this.jsbjs;
    }
    
    public void setJsbjs(Set jsbjs) {
        this.jsbjs = jsbjs;
    }

    public Set getXsxxes() {
        return this.xsxxes;
    }
    
    public void setXsxxes(Set xsxxes) {
        this.xsxxes = xsxxes;
    }

    public Set getGgxxes() {
        return this.ggxxes;
    }
    
    public void setGgxxes(Set ggxxes) {
        this.ggxxes = ggxxes;
    }


	/**
	 * @return the xxmc
	 */
	public String getXxmc() {
		return xxmc;
	}


	/**
	 * @param xxmc the xxmc to set
	 */
	public void setXxmc(String xxmc) {
		this.xxmc = xxmc;
	}
   








}