package com.whjbsoft.www.po;



/**
 * Ccrydd generated by MyEclipse - Hibernate Tools
 */

public class Ccrydd  implements java.io.Serializable {


    // Fields    

     private CcryddId id;
     private Ygxx ygxx;
     private Crkdd crkdd;


    // Constructors

    /** default constructor */
    public Ccrydd() {
    }

    
    /** full constructor */
    public Ccrydd(Ygxx ygxx, Crkdd crkdd) {
        this.ygxx = ygxx;
        this.crkdd = crkdd;
    }

   
    // Property accessors

    public CcryddId getId() {
        return this.id;
    }
    
    public void setId(CcryddId id) {
        this.id = id;
    }

    public Ygxx getYgxx() {
        return this.ygxx;
    }
    
    public void setYgxx(Ygxx ygxx) {
        this.ygxx = ygxx;
    }

    public Crkdd getCrkdd() {
        return this.crkdd;
    }
    
    public void setCrkdd(Crkdd crkdd) {
        this.crkdd = crkdd;
    }
   








}