package com.whjbsoft.www.po;



/**
 * CcryddId generated by MyEclipse - Hibernate Tools
 */

public class CcryddId  implements java.io.Serializable {


    // Fields    

     private Integer crkzj;
     private Integer ygzj;


    // Constructors

    /** default constructor */
    public CcryddId() {
    }

    
    /** full constructor */
    public CcryddId(Integer crkzj, Integer ygzj) {
        this.crkzj = crkzj;
        this.ygzj = ygzj;
    }

   
    // Property accessors

    public Integer getCrkzj() {
        return this.crkzj;
    }
    
    public void setCrkzj(Integer crkzj) {
        this.crkzj = crkzj;
    }

    public Integer getYgzj() {
        return this.ygzj;
    }
    
    public void setYgzj(Integer ygzj) {
        this.ygzj = ygzj;
    }
   



   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof CcryddId) ) return false;
		 CcryddId castOther = ( CcryddId ) other; 
         
		 return ( (this.getCrkzj()==castOther.getCrkzj()) || ( this.getCrkzj()!=null && castOther.getCrkzj()!=null && this.getCrkzj().equals(castOther.getCrkzj()) ) )
 && ( (this.getYgzj()==castOther.getYgzj()) || ( this.getYgzj()!=null && castOther.getYgzj()!=null && this.getYgzj().equals(castOther.getYgzj()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getCrkzj() == null ? 0 : this.getCrkzj().hashCode() );
         result = 37 * result + ( getYgzj() == null ? 0 : this.getYgzj().hashCode() );
         return result;
   }   





}