package com.whjbsoft.www.po;

import java.util.HashSet;
import java.util.Set;



/**
 * Crkhp generated by MyEclipse - Hibernate Tools
 */

public class Crkhp  implements java.io.Serializable,Comparable<Crkhp>{


	private Integer crkhpzj;
     private Crkdd crkdd;
     private String hpbm;
     private String hpmc;
     private String txm;
     private String hpdw;
     private String hplx;
     private String hpxh;
     private String hpgg;
     private Double hpsl;
     private Double hptj;
     private Double hpdj;
     private String tjdw;
     private Double hgsl;
     private Double shsl;
     private Set crkhps = new HashSet(0);

    // Constructors

    /** default constructor */
    public Crkhp() {
    }

    

   
    // Property accessors

    public Integer getCrkhpzj() {
        return this.crkhpzj;
    }
    
    public void setCrkhpzj(Integer crkhpzj) {
        this.crkhpzj = crkhpzj;
    }

    public Crkdd getCrkdd() {
        return this.crkdd;
    }
    
    public void setCrkdd(Crkdd crkdd) {
        this.crkdd = crkdd;
    }

    public String getHpbm() {
        return this.hpbm;
    }
    
    public void setHpbm(String hpbm) {
        this.hpbm = hpbm;
    }

    public String getHpmc() {
        return this.hpmc;
    }
    
    public void setHpmc(String hpmc) {
        this.hpmc = hpmc;
    }

    public String getHpdw() {
        return this.hpdw;
    }
    
    public void setHpdw(String hpdw) {
        this.hpdw = hpdw;
    }

    public String getHplx() {
        return this.hplx;
    }
    
    public void setHplx(String hplx) {
        this.hplx = hplx;
    }

    public String getHpxh() {
        return this.hpxh;
    }
    
    public void setHpxh(String hpxh) {
        this.hpxh = hpxh;
    }

    public String getHpgg() {
        return this.hpgg;
    }
    
    public void setHpgg(String hpgg) {
        this.hpgg = hpgg;
    }

    public Double getHpsl() {
        return this.hpsl;
    }
    
    public void setHpsl(Double hpsl) {
        this.hpsl = hpsl;
    }

    public Double getHptj() {
        return this.hptj;
    }
    
    public void setHptj(Double hptj) {
        this.hptj = hptj;
    }

    public Double getHpdj() {
        return this.hpdj;
    }
    
    public void setHpdj(Double hpdj) {
        this.hpdj = hpdj;
    }

    public Double getHgsl() {
        return this.hgsl;
    }
    
    public void setHgsl(Double hgsl) {
        this.hgsl = hgsl;
    }

    public Double getShsl() {
        return this.shsl;
    }
    
    public void setShsl(Double shsl) {
        this.shsl = shsl;
    }

	public String getTjdw() {
		return tjdw;
	}

	public void setTjdw(String tjdw) {
		this.tjdw = tjdw;
	}

	public Set getCrkhps() {
		return crkhps;
	}

	public void setCrkhps(Set crkhps) {
		this.crkhps = crkhps;
	}




	public String getTxm() {
		return txm;
	}




	public void setTxm(String txm) {
		this.txm = txm;
	}
	
	public int compareTo(Crkhp o) {
		return this.getCrkhpzj()-o.getCrkhpzj();
	}

}