package com.whjbsoft.www.po;



/**
 * Ggxx generated by MyEclipse - Hibernate Tools
 */

public class Ggxx  implements java.io.Serializable {


    // Fields    

     private Integer ggzj;
     private Bjxx bjxx;
     private String ggbt;
     private String ggzz;
     private String ggnr;
     private String fbsj;


    // Constructors

    /** default constructor */
    public Ggxx() {
    }

    
    /** full constructor */
    public Ggxx(Bjxx bjxx, String ggbt, String ggzz, String ggnr, String fbsj) {
        this.bjxx = bjxx;
        this.ggbt = ggbt;
        this.ggzz = ggzz;
        this.ggnr = ggnr;
        this.fbsj = fbsj;
    }

   
    // Property accessors

    public Integer getGgzj() {
        return this.ggzj;
    }
    
    public void setGgzj(Integer ggzj) {
        this.ggzj = ggzj;
    }

    public Bjxx getBjxx() {
        return this.bjxx;
    }
    
    public void setBjxx(Bjxx bjxx) {
        this.bjxx = bjxx;
    }

    public String getGgbt() {
        return this.ggbt;
    }
    
    public void setGgbt(String ggbt) {
        this.ggbt = ggbt;
    }

    public String getGgzz() {
        return this.ggzz;
    }
    
    public void setGgzz(String ggzz) {
        this.ggzz = ggzz;
    }

    public String getGgnr() {
        return this.ggnr;
    }
    
    public void setGgnr(String ggnr) {
        this.ggnr = ggnr;
    }

    public String getFbsj() {
        return this.fbsj;
    }
    
    public void setFbsj(String fbsj) {
        this.fbsj = fbsj;
    }
   








}