package com.whjbsoft.www.po;



/**
 * Hzgxxx generated by MyEclipse - Hibernate Tools
 */

public class Hzgxxx  implements java.io.Serializable {


    // Fields    

     private Integer hzgxzj;
     private String hzdbh;
     private String hzdwmc;
     private String hzdwlx;
     private String lxr;
     private String lxdh;
     private String lxrcz;
     private String dwdz;
     private String dwyb;
     private String xybh;
     private String khh;
     private String zh;
     private String frdb;
     private String qydm;
     private String yyzzhm;
     private String dsdjhm;
     private String gsdjhm;
     private String clsj;
     private Double zczj;
     private String dlysxkz;
     private String wxpysxkz;
     private String bzsm;
     private Integer ssxs;
     private Integer sssysz;


    // Constructors

    /** default constructor */
    public Hzgxxx() {
    }

    
    /** full constructor */
    public Hzgxxx(String hzdbh, String hzdwmc, String hzdwlx, String lxr, String lxdh, String lxrcz, String dwdz, String dwyb, String xybh, String khh, String zh, String frdb, String qydm, String yyzzhm, String dsdjhm, String gsdjhm, String clsj, Double zczj, String dlysxkz, String wxpysxkz, String bzsm, Integer ssxs, Integer sssysz) {
        this.hzdbh = hzdbh;
        this.hzdwmc = hzdwmc;
        this.hzdwlx = hzdwlx;
        this.lxr = lxr;
        this.lxdh = lxdh;
        this.lxrcz = lxrcz;
        this.dwdz = dwdz;
        this.dwyb = dwyb;
        this.xybh = xybh;
        this.khh = khh;
        this.zh = zh;
        this.frdb = frdb;
        this.qydm = qydm;
        this.yyzzhm = yyzzhm;
        this.dsdjhm = dsdjhm;
        this.gsdjhm = gsdjhm;
        this.clsj = clsj;
        this.zczj = zczj;
        this.dlysxkz = dlysxkz;
        this.wxpysxkz = wxpysxkz;
        this.bzsm = bzsm;
        this.ssxs = ssxs;
        this.sssysz = sssysz;
    }

   
    // Property accessors

    public Integer getHzgxzj() {
        return this.hzgxzj;
    }
    
    public void setHzgxzj(Integer hzgxzj) {
        this.hzgxzj = hzgxzj;
    }

    public String getHzdbh() {
        return this.hzdbh;
    }
    
    public void setHzdbh(String hzdbh) {
        this.hzdbh = hzdbh;
    }

    public String getHzdwmc() {
        return this.hzdwmc;
    }
    
    public void setHzdwmc(String hzdwmc) {
        this.hzdwmc = hzdwmc;
    }

    public String getHzdwlx() {
        return this.hzdwlx;
    }
    
    public void setHzdwlx(String hzdwlx) {
        this.hzdwlx = hzdwlx;
    }

    public String getLxr() {
        return this.lxr;
    }
    
    public void setLxr(String lxr) {
        this.lxr = lxr;
    }

    public String getLxdh() {
        return this.lxdh;
    }
    
    public void setLxdh(String lxdh) {
        this.lxdh = lxdh;
    }

    public String getLxrcz() {
        return this.lxrcz;
    }
    
    public void setLxrcz(String lxrcz) {
        this.lxrcz = lxrcz;
    }

    public String getDwdz() {
        return this.dwdz;
    }
    
    public void setDwdz(String dwdz) {
        this.dwdz = dwdz;
    }

    public String getDwyb() {
        return this.dwyb;
    }
    
    public void setDwyb(String dwyb) {
        this.dwyb = dwyb;
    }

    public String getXybh() {
        return this.xybh;
    }
    
    public void setXybh(String xybh) {
        this.xybh = xybh;
    }

    public String getKhh() {
        return this.khh;
    }
    
    public void setKhh(String khh) {
        this.khh = khh;
    }

    public String getZh() {
        return this.zh;
    }
    
    public void setZh(String zh) {
        this.zh = zh;
    }

    public String getFrdb() {
        return this.frdb;
    }
    
    public void setFrdb(String frdb) {
        this.frdb = frdb;
    }

    public String getQydm() {
        return this.qydm;
    }
    
    public void setQydm(String qydm) {
        this.qydm = qydm;
    }

    public String getYyzzhm() {
        return this.yyzzhm;
    }
    
    public void setYyzzhm(String yyzzhm) {
        this.yyzzhm = yyzzhm;
    }

    public String getDsdjhm() {
        return this.dsdjhm;
    }
    
    public void setDsdjhm(String dsdjhm) {
        this.dsdjhm = dsdjhm;
    }

    public String getGsdjhm() {
        return this.gsdjhm;
    }
    
    public void setGsdjhm(String gsdjhm) {
        this.gsdjhm = gsdjhm;
    }

    public String getClsj() {
        return this.clsj;
    }
    
    public void setClsj(String clsj) {
        this.clsj = clsj;
    }

    public Double getZczj() {
        return this.zczj;
    }
    
    public void setZczj(Double zczj) {
        this.zczj = zczj;
    }

    public String getDlysxkz() {
        return this.dlysxkz;
    }
    
    public void setDlysxkz(String dlysxkz) {
        this.dlysxkz = dlysxkz;
    }

    public String getWxpysxkz() {
        return this.wxpysxkz;
    }
    
    public void setWxpysxkz(String wxpysxkz) {
        this.wxpysxkz = wxpysxkz;
    }

    public String getBzsm() {
        return this.bzsm;
    }
    
    public void setBzsm(String bzsm) {
        this.bzsm = bzsm;
    }

    public Integer getSsxs() {
        return this.ssxs;
    }
    
    public void setSsxs(Integer ssxs) {
        this.ssxs = ssxs;
    }

    public Integer getSssysz() {
        return this.sssysz;
    }
    
    public void setSssysz(Integer sssysz) {
        this.sssysz = sssysz;
    }
   








}