package com.whjbsoft.www.po;



/**
 * Jsbj generated by MyEclipse - Hibernate Tools
 */

public class Jsbj  implements java.io.Serializable {


    // Fields    

     private JsbjId id;
     private Bjxx bjxx;
     private Jsgl jsgl;


    // Constructors

    /** default constructor */
    public Jsbj() {
    }

    
    /** full constructor */
    public Jsbj(Bjxx bjxx, Jsgl jsgl) {
        this.bjxx = bjxx;
        this.jsgl = jsgl;
    }

   
    // Property accessors

    public JsbjId getId() {
        return this.id;
    }
    
    public void setId(JsbjId id) {
        this.id = id;
    }

    public Bjxx getBjxx() {
        return this.bjxx;
    }
    
    public void setBjxx(Bjxx bjxx) {
        this.bjxx = bjxx;
    }

    public Jsgl getJsgl() {
        return this.jsgl;
    }
    
    public void setJsgl(Jsgl jsgl) {
        this.jsgl = jsgl;
    }
   








}