package com.whjbsoft.www.po;



/**
 * Kfcppdb generated by MyEclipse - Hibernate Tools
 */

public class Kfcppdb  implements java.io.Serializable {


    // Fields    

     private Integer kfpdzj;
     private Pddd pddd;
     private String hpbm;
     private String hpmc;
     private Double qckc;
     private Double rksl;
     private Double cksl;
     private Double qmkc;
     private Double pysl;
     private Double pksl;
     private String ph;


    // Constructors

    /** default constructor */
    public Kfcppdb() {
    }

    
    /** full constructor */
    public Kfcppdb(Pddd pddd, String hpbm, String hpmc, Double qckc, Double rksl, Double cksl, Double qmkc, Double pysl, Double pksl, String ph) {
        this.pddd = pddd;
        this.hpbm = hpbm;
        this.hpmc = hpmc;
        this.qckc = qckc;
        this.rksl = rksl;
        this.cksl = cksl;
        this.qmkc = qmkc;
        this.pysl = pysl;
        this.pksl = pksl;
        this.ph = ph;
    }

   
    // Property accessors

    public Integer getKfpdzj() {
        return this.kfpdzj;
    }
    
    public void setKfpdzj(Integer kfpdzj) {
        this.kfpdzj = kfpdzj;
    }

    public Pddd getPddd() {
        return this.pddd;
    }
    
    public void setPddd(Pddd pddd) {
        this.pddd = pddd;
    }

    public String getHpbm() {
        return this.hpbm;
    }
    
    public void setHpbm(String hpbm) {
        this.hpbm = hpbm;
    }

    public String getHpmc() {
        return this.hpmc;
    }
    
    public void setHpmc(String hpmc) {
        this.hpmc = hpmc;
    }

    public Double getQckc() {
        return this.qckc;
    }
    
    public void setQckc(Double qckc) {
        this.qckc = qckc;
    }

    public Double getRksl() {
        return this.rksl;
    }
    
    public void setRksl(Double rksl) {
        this.rksl = rksl;
    }

    public Double getCksl() {
        return this.cksl;
    }
    
    public void setCksl(Double cksl) {
        this.cksl = cksl;
    }

    public Double getQmkc() {
        return this.qmkc;
    }
    
    public void setQmkc(Double qmkc) {
        this.qmkc = qmkc;
    }

    public Double getPysl() {
        return this.pysl;
    }
    
    public void setPysl(Double pysl) {
        this.pysl = pysl;
    }

    public Double getPksl() {
        return this.pksl;
    }
    
    public void setPksl(Double pksl) {
        this.pksl = pksl;
    }

    public String getPh() {
        return this.ph;
    }
    
    public void setPh(String ph) {
        this.ph = ph;
    }
   








}