package com.whjbsoft.www.po;

import java.util.HashSet;
import java.util.Set;


/**
 * Kfxx generated by MyEclipse - Hibernate Tools
 */

public class Kfxx  implements java.io.Serializable {


    // Fields    

     private Integer kfzj;
     private String kfbh;
     private String pym;
     private String kflx;
     private String kfmc;
     private Double kfcd;
     private Double kfkd;
     private Double kfgd;
     private Double kfmj;
     private Double tdkd;
     private Double xzbj;
     private String kflxdh;
     private String czhm;
     private String kfxxdz;
     private String kfzt;
     private Integer ssxs;
     private Integer sssysz;
     private String ssjg;
     private String kfgly;
     private String bzxx;
     private Set sbxxes = new HashSet(0);
     private Set qwxxes = new HashSet(0);


    // Constructors

    /** default constructor */
    public Kfxx() {
    }

    
    /** full constructor */
    public Kfxx(String kfbh, String pym, String kflx, String kfmc, Double kfcd, Double kfkd, Double kfgd, Double kfmj, Double tdkd, Double xzbj, String kflxdh, String czhm, String kfxxdz, String kfzt, Integer ssxs, Integer sssysz, String ssjg, String kfgly, String bzxx, Set sbxxes, Set qwxxes) {
        this.kfbh = kfbh;
        this.pym = pym;
        this.kflx = kflx;
        this.kfmc = kfmc;
        this.kfcd = kfcd;
        this.kfkd = kfkd;
        this.kfgd = kfgd;
        this.kfmj = kfmj;
        this.tdkd = tdkd;
        this.xzbj = xzbj;
        this.kflxdh = kflxdh;
        this.czhm = czhm;
        this.kfxxdz = kfxxdz;
        this.kfzt = kfzt;
        this.ssxs = ssxs;
        this.sssysz = sssysz;
        this.ssjg = ssjg;
        this.kfgly = kfgly;
        this.bzxx = bzxx;
        this.sbxxes = sbxxes;
        this.qwxxes = qwxxes;
    }

   
    // Property accessors

    public Integer getKfzj() {
        return this.kfzj;
    }
    
    public void setKfzj(Integer kfzj) {
        this.kfzj = kfzj;
    }

    public String getKfbh() {
        return this.kfbh;
    }
    
    public void setKfbh(String kfbh) {
        this.kfbh = kfbh;
    }

    public String getPym() {
        return this.pym;
    }
    
    public void setPym(String pym) {
        this.pym = pym;
    }

    public String getKflx() {
        return this.kflx;
    }
    
    public void setKflx(String kflx) {
        this.kflx = kflx;
    }

    public String getKfmc() {
        return this.kfmc;
    }
    
    public void setKfmc(String kfmc) {
        this.kfmc = kfmc;
    }

    public Double getKfcd() {
        return this.kfcd;
    }
    
    public void setKfcd(Double kfcd) {
        this.kfcd = kfcd;
    }

    public Double getKfkd() {
        return this.kfkd;
    }
    
    public void setKfkd(Double kfkd) {
        this.kfkd = kfkd;
    }

    public Double getKfgd() {
        return this.kfgd;
    }
    
    public void setKfgd(Double kfgd) {
        this.kfgd = kfgd;
    }

    public Double getKfmj() {
        return this.kfmj;
    }
    
    public void setKfmj(Double kfmj) {
        this.kfmj = kfmj;
    }

    public Double getTdkd() {
        return this.tdkd;
    }
    
    public void setTdkd(Double tdkd) {
        this.tdkd = tdkd;
    }

    public Double getXzbj() {
        return this.xzbj;
    }
    
    public void setXzbj(Double xzbj) {
        this.xzbj = xzbj;
    }

    public String getKflxdh() {
        return this.kflxdh;
    }
    
    public void setKflxdh(String kflxdh) {
        this.kflxdh = kflxdh;
    }

    public String getCzhm() {
        return this.czhm;
    }
    
    public void setCzhm(String czhm) {
        this.czhm = czhm;
    }

    public String getKfxxdz() {
        return this.kfxxdz;
    }
    
    public void setKfxxdz(String kfxxdz) {
        this.kfxxdz = kfxxdz;
    }

    public String getKfzt() {
        return this.kfzt;
    }
    
    public void setKfzt(String kfzt) {
        this.kfzt = kfzt;
    }

    public Integer getSsxs() {
        return this.ssxs;
    }
    
    public void setSsxs(Integer ssxs) {
        this.ssxs = ssxs;
    }

    public Integer getSssysz() {
        return this.sssysz;
    }
    
    public void setSssysz(Integer sssysz) {
        this.sssysz = sssysz;
    }

    public String getSsjg() {
        return this.ssjg;
    }
    
    public void setSsjg(String ssjg) {
        this.ssjg = ssjg;
    }

    public String getKfgly() {
        return this.kfgly;
    }
    
    public void setKfgly(String kfgly) {
        this.kfgly = kfgly;
    }

    public String getBzxx() {
        return this.bzxx;
    }
    
    public void setBzxx(String bzxx) {
        this.bzxx = bzxx;
    }

    public Set getSbxxes() {
        return this.sbxxes;
    }
    
    public void setSbxxes(Set sbxxes) {
        this.sbxxes = sbxxes;
    }

    public Set getQwxxes() {
        return this.qwxxes;
    }
    
    public void setQwxxes(Set qwxxes) {
        this.qwxxes = qwxxes;
    }
   








}