package com.whjbsoft.www.po;

import java.util.HashSet;
import java.util.Set;


/**
 * Khdd generated by MyEclipse - Hibernate Tools
 */

public class Khdd  implements java.io.Serializable {


    // Fields    

     private Integer ddzj;
     private Khxx khxxByKhzj;
     private Khxx khxxByKhxKhzj;
     private String ddbh;
     private String ddrq;
     private String qhrq;
     private Integer ddzt;
     private String zdr;
     private Integer ssxs;
     private Integer sssysz;
     private Set khhts = new HashSet(0);
     private Set khddhpbs = new HashSet(0);


    // Constructors

    /** default constructor */
    public Khdd() {
    }

    
    /** full constructor */
    public Khdd(Khxx khxxByKhzj, Khxx khxxByKhxKhzj, String ddbh, String ddrq, String qhrq, Integer ddzt, String zdr, Integer ssxs, Integer sssysz, Set khhts, Set khddhpbs) {
        this.khxxByKhzj = khxxByKhzj;
        this.khxxByKhxKhzj = khxxByKhxKhzj;
        this.ddbh = ddbh;
        this.ddrq = ddrq;
        this.qhrq = qhrq;
        this.ddzt = ddzt;
        this.zdr = zdr;
        this.ssxs = ssxs;
        this.sssysz = sssysz;
        this.khhts = khhts;
        this.khddhpbs = khddhpbs;
    }

   
    // Property accessors

    public Integer getDdzj() {
        return this.ddzj;
    }
    
    public void setDdzj(Integer ddzj) {
        this.ddzj = ddzj;
    }

    public Khxx getKhxxByKhzj() {
        return this.khxxByKhzj;
    }
    
    public void setKhxxByKhzj(Khxx khxxByKhzj) {
        this.khxxByKhzj = khxxByKhzj;
    }

    public Khxx getKhxxByKhxKhzj() {
        return this.khxxByKhxKhzj;
    }
    
    public void setKhxxByKhxKhzj(Khxx khxxByKhxKhzj) {
        this.khxxByKhxKhzj = khxxByKhxKhzj;
    }

    public String getDdbh() {
        return this.ddbh;
    }
    
    public void setDdbh(String ddbh) {
        this.ddbh = ddbh;
    }

    public String getDdrq() {
        return this.ddrq;
    }
    
    public void setDdrq(String ddrq) {
        this.ddrq = ddrq;
    }

    public String getQhrq() {
        return this.qhrq;
    }
    
    public void setQhrq(String qhrq) {
        this.qhrq = qhrq;
    }

    public Integer getDdzt() {
        return this.ddzt;
    }
    
    public void setDdzt(Integer ddzt) {
        this.ddzt = ddzt;
    }

    public String getZdr() {
        return this.zdr;
    }
    
    public void setZdr(String zdr) {
        this.zdr = zdr;
    }

    public Integer getSsxs() {
        return this.ssxs;
    }
    
    public void setSsxs(Integer ssxs) {
        this.ssxs = ssxs;
    }

    public Integer getSssysz() {
        return this.sssysz;
    }
    
    public void setSssysz(Integer sssysz) {
        this.sssysz = sssysz;
    }

    public Set getKhhts() {
        return this.khhts;
    }
    
    public void setKhhts(Set khhts) {
        this.khhts = khhts;
    }

    public Set getKhddhpbs() {
        return this.khddhpbs;
    }
    
    public void setKhddhpbs(Set khddhpbs) {
        this.khddhpbs = khddhpbs;
    }
   








}