package com.whjbsoft.www.po;



/**
 * Khts generated by MyEclipse - Hibernate Tools
 */

public class Khts  implements java.io.Serializable {


    // Fields    

     private Integer tszj;
     private String tskh;
     private String tsr;
     private String tsrq;
     private String tsnr;
     private String tsrdh;
     private String slr;
     private String slrq;
     private String slhf;
     private Integer ssxs;
     private Integer sssysz;
     private String tsbh;
     private Integer sfsl;


    // Constructors

    /** default constructor */
    public Khts() {
    }

    
    /** full constructor */
    public Khts(String tskh, String tsr, String tsrq, String tsnr, String tsrdh, String slr, String slrq, String slhf, Integer ssxs, Integer sssysz, String tsbh, Integer sfsl) {
        this.tskh = tskh;
        this.tsr = tsr;
        this.tsrq = tsrq;
        this.tsnr = tsnr;
        this.tsrdh = tsrdh;
        this.slr = slr;
        this.slrq = slrq;
        this.slhf = slhf;
        this.ssxs = ssxs;
        this.sssysz = sssysz;
        this.tsbh = tsbh;
        this.sfsl = sfsl;
    }

   
    // Property accessors

    public Integer getTszj() {
        return this.tszj;
    }
    
    public void setTszj(Integer tszj) {
        this.tszj = tszj;
    }

    public String getTskh() {
        return this.tskh;
    }
    
    public void setTskh(String tskh) {
        this.tskh = tskh;
    }

    public String getTsr() {
        return this.tsr;
    }
    
    public void setTsr(String tsr) {
        this.tsr = tsr;
    }

    public String getTsrq() {
        return this.tsrq;
    }
    
    public void setTsrq(String tsrq) {
        this.tsrq = tsrq;
    }

    public String getTsnr() {
        return this.tsnr;
    }
    
    public void setTsnr(String tsnr) {
        this.tsnr = tsnr;
    }

    public String getTsrdh() {
        return this.tsrdh;
    }
    
    public void setTsrdh(String tsrdh) {
        this.tsrdh = tsrdh;
    }

    public String getSlr() {
        return this.slr;
    }
    
    public void setSlr(String slr) {
        this.slr = slr;
    }

    public String getSlrq() {
        return this.slrq;
    }
    
    public void setSlrq(String slrq) {
        this.slrq = slrq;
    }

    public String getSlhf() {
        return this.slhf;
    }
    
    public void setSlhf(String slhf) {
        this.slhf = slhf;
    }

    public Integer getSsxs() {
        return this.ssxs;
    }
    
    public void setSsxs(Integer ssxs) {
        this.ssxs = ssxs;
    }

    public Integer getSssysz() {
        return this.sssysz;
    }
    
    public void setSssysz(Integer sssysz) {
        this.sssysz = sssysz;
    }

    public String getTsbh() {
        return this.tsbh;
    }
    
    public void setTsbh(String tsbh) {
        this.tsbh = tsbh;
    }

    public Integer getSfsl() {
        return this.sfsl;
    }
    
    public void setSfsl(Integer sfsl) {
        this.sfsl = sfsl;
    }
   








}