package com.whjbsoft.www.po;

import java.util.HashSet;
import java.util.Set;


/**
 * Khxx generated by MyEclipse - Hibernate Tools
 */

public class Khxx  implements java.io.Serializable {


    // Fields    

     private Integer khzj;
     private String khbh;
     private String dwmc;
     private String khjl;
     private String khjldh;
     private String khjb;
     private String lxr;
     private String lxrdh;
     private String lxrcz;
     private String lxryx;
     private String lxryb;
     private String ssjg;
     private String khdz;
     private String hysx;
     private String khms;
     private String khh;
     private String khzh;
     private String zdr;
     private String zdsj;
     private Integer ssxs;
     private Integer sssysz;
     private Integer sftzwl;
     private Set khddsForKhxKhzj = new HashSet(0);
     private Set khddsForKhzj = new HashSet(0);


    // Constructors

    /** default constructor */
    public Khxx() {
    }

    
    /** full constructor */
    public Khxx(String khbh, String dwmc, String khjl, String khjldh, String khjb, String lxr, String lxrdh, String lxrcz, String lxryx, String lxryb, String ssjg, String khdz, String hysx, String khms, String khh, String khzh, String zdr, String zdsj, Integer ssxs, Integer sssysz, Integer sftzwl, Set khddsForKhxKhzj, Set khddsForKhzj) {
        this.khbh = khbh;
        this.dwmc = dwmc;
        this.khjl = khjl;
        this.khjldh = khjldh;
        this.khjb = khjb;
        this.lxr = lxr;
        this.lxrdh = lxrdh;
        this.lxrcz = lxrcz;
        this.lxryx = lxryx;
        this.lxryb = lxryb;
        this.ssjg = ssjg;
        this.khdz = khdz;
        this.hysx = hysx;
        this.khms = khms;
        this.khh = khh;
        this.khzh = khzh;
        this.zdr = zdr;
        this.zdsj = zdsj;
        this.ssxs = ssxs;
        this.sssysz = sssysz;
        this.sftzwl = sftzwl;
        this.khddsForKhxKhzj = khddsForKhxKhzj;
        this.khddsForKhzj = khddsForKhzj;
    }

   
    // Property accessors

    public Integer getKhzj() {
        return this.khzj;
    }
    
    public void setKhzj(Integer khzj) {
        this.khzj = khzj;
    }

    public String getKhbh() {
        return this.khbh;
    }
    
    public void setKhbh(String khbh) {
        this.khbh = khbh;
    }

    public String getDwmc() {
        return this.dwmc;
    }
    
    public void setDwmc(String dwmc) {
        this.dwmc = dwmc;
    }

    public String getKhjl() {
        return this.khjl;
    }
    
    public void setKhjl(String khjl) {
        this.khjl = khjl;
    }

    public String getKhjldh() {
        return this.khjldh;
    }
    
    public void setKhjldh(String khjldh) {
        this.khjldh = khjldh;
    }

    public String getKhjb() {
        return this.khjb;
    }
    
    public void setKhjb(String khjb) {
        this.khjb = khjb;
    }

    public String getLxr() {
        return this.lxr;
    }
    
    public void setLxr(String lxr) {
        this.lxr = lxr;
    }

    public String getLxrdh() {
        return this.lxrdh;
    }
    
    public void setLxrdh(String lxrdh) {
        this.lxrdh = lxrdh;
    }

    public String getLxrcz() {
        return this.lxrcz;
    }
    
    public void setLxrcz(String lxrcz) {
        this.lxrcz = lxrcz;
    }

    public String getLxryx() {
        return this.lxryx;
    }
    
    public void setLxryx(String lxryx) {
        this.lxryx = lxryx;
    }

    public String getLxryb() {
        return this.lxryb;
    }
    
    public void setLxryb(String lxryb) {
        this.lxryb = lxryb;
    }

    public String getSsjg() {
        return this.ssjg;
    }
    
    public void setSsjg(String ssjg) {
        this.ssjg = ssjg;
    }

    public String getKhdz() {
        return this.khdz;
    }
    
    public void setKhdz(String khdz) {
        this.khdz = khdz;
    }

    public String getHysx() {
        return this.hysx;
    }
    
    public void setHysx(String hysx) {
        this.hysx = hysx;
    }

    public String getKhms() {
        return this.khms;
    }
    
    public void setKhms(String khms) {
        this.khms = khms;
    }

    public String getKhh() {
        return this.khh;
    }
    
    public void setKhh(String khh) {
        this.khh = khh;
    }

    public String getKhzh() {
        return this.khzh;
    }
    
    public void setKhzh(String khzh) {
        this.khzh = khzh;
    }

    public String getZdr() {
        return this.zdr;
    }
    
    public void setZdr(String zdr) {
        this.zdr = zdr;
    }

    public String getZdsj() {
        return this.zdsj;
    }
    
    public void setZdsj(String zdsj) {
        this.zdsj = zdsj;
    }

    public Integer getSsxs() {
        return this.ssxs;
    }
    
    public void setSsxs(Integer ssxs) {
        this.ssxs = ssxs;
    }

    public Integer getSssysz() {
        return this.sssysz;
    }
    
    public void setSssysz(Integer sssysz) {
        this.sssysz = sssysz;
    }

    public Integer getSftzwl() {
        return this.sftzwl;
    }
    
    public void setSftzwl(Integer sftzwl) {
        this.sftzwl = sftzwl;
    }

    public Set getKhddsForKhxKhzj() {
        return this.khddsForKhxKhzj;
    }
    
    public void setKhddsForKhxKhzj(Set khddsForKhxKhzj) {
        this.khddsForKhxKhzj = khddsForKhxKhzj;
    }

    public Set getKhddsForKhzj() {
        return this.khddsForKhzj;
    }
    
    public void setKhddsForKhzj(Set khddsForKhzj) {
        this.khddsForKhzj = khddsForKhzj;
    }
   








}