package com.whjbsoft.www.po;

import java.util.HashSet;
import java.util.Set;


/**
 * Qwxx generated by MyEclipse - Hibernate Tools
 */

public class Qwxx  implements java.io.Serializable {


    // Fields    

     private Integer qwzj;
     private Kfxx kfxx;
     private String qwbh;
     private String qwmc;
     private String ccgn;
     private String cclx;
     private String ccfs;
     private String cchj;
     private String ccpz;
     private Integer sffpcw;
     private Integer qfabm;
     private Integer amhs;
     private Integer amls;
     private Integer bmhs;
     private Integer bmls;
     private Set cwxxes = new HashSet(0);


    // Constructors

    /** default constructor */
    public Qwxx() {
    }

    
    /** full constructor */
    public Qwxx(Kfxx kfxx, String qwbh, String qwmc, String ccgn, String cclx, String ccfs, String cchj, String ccpz, Set cwxxes) {
        this.kfxx = kfxx;
        this.qwbh = qwbh;
        this.qwmc = qwmc;
        this.ccgn = ccgn;
        this.cclx = cclx;
        this.ccfs = ccfs;
        this.cchj = cchj;
        this.ccpz = ccpz;
        this.cwxxes = cwxxes;
    }

   
    // Property accessors

    public Integer getQwzj() {
        return this.qwzj;
    }
    
    public void setQwzj(Integer qwzj) {
        this.qwzj = qwzj;
    }

    public Kfxx getKfxx() {
        return this.kfxx;
    }
    
    public void setKfxx(Kfxx kfxx) {
        this.kfxx = kfxx;
    }

    public String getQwbh() {
        return this.qwbh;
    }
    
    public void setQwbh(String qwbh) {
        this.qwbh = qwbh;
    }

    public String getQwmc() {
        return this.qwmc;
    }
    
    public void setQwmc(String qwmc) {
        this.qwmc = qwmc;
    }

    public String getCcgn() {
        return this.ccgn;
    }
    
    public void setCcgn(String ccgn) {
        this.ccgn = ccgn;
    }

    public String getCclx() {
        return this.cclx;
    }
    
    public void setCclx(String cclx) {
        this.cclx = cclx;
    }

    public String getCcfs() {
        return this.ccfs;
    }
    
    public void setCcfs(String ccfs) {
        this.ccfs = ccfs;
    }

    public String getCchj() {
        return this.cchj;
    }
    
    public void setCchj(String cchj) {
        this.cchj = cchj;
    }

    public String getCcpz() {
        return this.ccpz;
    }
    
    public void setCcpz(String ccpz) {
        this.ccpz = ccpz;
    }

    public Set getCwxxes() {
        return this.cwxxes;
    }
    
    public void setCwxxes(Set cwxxes) {
        this.cwxxes = cwxxes;
    }
	public Integer getAmhs() {
		return amhs;
	}
	public void setAmhs(Integer amhs) {
		this.amhs = amhs;
	}

	public Integer getAmls() {
		return amls;
	}

	public void setAmls(Integer amls) {
		this.amls = amls;
	}

	public Integer getBmhs() {
		return bmhs;
	}

	public void setBmhs(Integer bmhs) {
		this.bmhs = bmhs;
	}

	public Integer getBmls() {
		return bmls;
	}

	public void setBmls(Integer bmls) {
		this.bmls = bmls;
	}

	public Integer getQfabm() {
		return qfabm;
	}

	public void setQfabm(Integer qfabm) {
		this.qfabm = qfabm;
	}


	public Integer getSffpcw() {
		return sffpcw;
	}


	public void setSffpcw(Integer sffpcw) {
		this.sffpcw = sffpcw;
	}

}