package com.whjbsoft.www.po;

import java.util.HashSet;
import java.util.Set;


/**
 * Sjzd generated by MyEclipse - Hibernate Tools
 */

public class Sjzd  implements java.io.Serializable {


    // Fields    

     private Integer sjzdzj;
     private String sjzdmc;
     private Set sjzdmxes = new HashSet(0);


    // Constructors

    /** default constructor */
    public Sjzd() {
    }

    
    /** full constructor */
    public Sjzd(String sjzdmc, Set sjzdmxes) {
        this.sjzdmc = sjzdmc;
        this.sjzdmxes = sjzdmxes;
    }

   
    // Property accessors

    public Integer getSjzdzj() {
        return this.sjzdzj;
    }
    
    public void setSjzdzj(Integer sjzdzj) {
        this.sjzdzj = sjzdzj;
    }

    public String getSjzdmc() {
        return this.sjzdmc;
    }
    
    public void setSjzdmc(String sjzdmc) {
        this.sjzdmc = sjzdmc;
    }

    public Set getSjzdmxes() {
        return this.sjzdmxes;
    }
    
    public void setSjzdmxes(Set sjzdmxes) {
        this.sjzdmxes = sjzdmxes;
    }
   








}