package com.whjbsoft.www.po;



/**
 * Sysj generated by MyEclipse - Hibernate Tools
 */

public class Sysj  implements java.io.Serializable {


    // Fields    

     private SysjId id;
     private Sjxx sjxx;
     private Sysz sysz;


    // Constructors

    /** default constructor */
    public Sysj() {
    }

    
    /** full constructor */
    public Sysj(Sjxx sjxx, Sysz sysz) {
        this.sjxx = sjxx;
        this.sysz = sysz;
    }

   
    // Property accessors

    public SysjId getId() {
        return this.id;
    }
    
    public void setId(SysjId id) {
        this.id = id;
    }

    public Sjxx getSjxx() {
        return this.sjxx;
    }
    
    public void setSjxx(Sjxx sjxx) {
        this.sjxx = sjxx;
    }

    public Sysz getSysz() {
        return this.sysz;
    }
    
    public void setSysz(Sysz sysz) {
        this.sysz = sysz;
    }
   








}