package com.whjbsoft.www.po;



/**
 * XlyhId generated by MyEclipse - Hibernate Tools
 */

public class XlyhId  implements java.io.Serializable {


    // Fields    

     private Integer bxzj;
     private Integer ysddzj;


    // Constructors

    /** default constructor */
    public XlyhId() {
    }

    
    /** full constructor */
    public XlyhId(Integer bxzj, Integer ysddzj) {
        this.bxzj = bxzj;
        this.ysddzj = ysddzj;
    }

   
    // Property accessors

    public Integer getBxzj() {
        return this.bxzj;
    }
    
    public void setBxzj(Integer bxzj) {
        this.bxzj = bxzj;
    }

    public Integer getYsddzj() {
        return this.ysddzj;
    }
    
    public void setYsddzj(Integer ysddzj) {
        this.ysddzj = ysddzj;
    }
   



   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof XlyhId) ) return false;
		 XlyhId castOther = ( XlyhId ) other; 
         
		 return ( (this.getBxzj()==castOther.getBxzj()) || ( this.getBxzj()!=null && castOther.getBxzj()!=null && this.getBxzj().equals(castOther.getBxzj()) ) )
 && ( (this.getYsddzj()==castOther.getYsddzj()) || ( this.getYsddzj()!=null && castOther.getYsddzj()!=null && this.getYsddzj().equals(castOther.getYsddzj()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getBxzj() == null ? 0 : this.getBxzj().hashCode() );
         result = 37 * result + ( getYsddzj() == null ? 0 : this.getYsddzj().hashCode() );
         return result;
   }   





}