package com.whjbsoft.www.po;

import java.util.HashSet;
import java.util.Set;


/**
 * Xsxx generated by MyEclipse - Hibernate Tools
 */

public class Xsxx  implements java.io.Serializable {


    // Fields    

     private Integer xszj;
     private Bjxx bjxx;
     private String xsxh;
     private String xsxm;
     private String xsmm;
     private Integer yxbj;
     private String bzxx;
     private Integer sfdl;
     private String zhdlsj;
     private String zhsyrwmc;
     private Integer sssyz;
     private Integer sssysz;
     private Set djxxes = new HashSet(0);
     private Set xsgwxxes = new HashSet(0);
     private String rxsj;
     private String xb;
     private String xsdh;
     private String xsdz;
     private String zjhm;
     private String xsjg;
     private Set djxxess = new HashSet(0);

    // Constructors

    public Set getDjxxess() {
		return djxxess;
	}


	public void setDjxxess(Set djxxess) {
		this.djxxess = djxxess;
	}


	public String getRxsj() {
		return rxsj;
	}


	public void setRxsj(String rxsj) {
		this.rxsj = rxsj;
	}


	public String getXb() {
		return xb;
	}


	public void setXb(String xb) {
		this.xb = xb;
	}


	public String getXsdh() {
		return xsdh;
	}


	public void setXsdh(String xsdh) {
		this.xsdh = xsdh;
	}


	public String getXsdz() {
		return xsdz;
	}


	public void setXsdz(String xsdz) {
		this.xsdz = xsdz;
	}


	public String getZjhm() {
		return zjhm;
	}


	public void setZjhm(String zjhm) {
		this.zjhm = zjhm;
	}


	public String getXsjg() {
		return xsjg;
	}


	public void setXsjg(String xsjg) {
		this.xsjg = xsjg;
	}


	/** default constructor */
    public Xsxx() {
    }

    
    /** full constructor */
    public Xsxx(Bjxx bjxx, String xsxh, String xsxm, String xsmm, Integer yxbj, String bzxx, Integer sfdl, String zhdlsj, String zhsyrwmc, Integer sssysz, Set djxxes) {
        this.bjxx = bjxx;
        this.xsxh = xsxh;
        this.xsxm = xsxm;
        this.xsmm = xsmm;
        this.yxbj = yxbj;
        this.bzxx = bzxx;
        this.sfdl = sfdl;
        this.zhdlsj = zhdlsj;
        this.zhsyrwmc = zhsyrwmc;
        this.sssysz = sssysz;
        this.djxxes = djxxes;
    }

   
    // Property accessors

    public Integer getXszj() {
        return this.xszj;
    }
    
    public void setXszj(Integer xszj) {
        this.xszj = xszj;
    }

    public Bjxx getBjxx() {
        return this.bjxx;
    }
    
    public void setBjxx(Bjxx bjxx) {
        this.bjxx = bjxx;
    }

    public String getXsxh() {
        return this.xsxh;
    }
    
    public void setXsxh(String xsxh) {
        this.xsxh = xsxh;
    }

    public String getXsxm() {
        return this.xsxm;
    }
    
    public void setXsxm(String xsxm) {
        this.xsxm = xsxm;
    }

    public String getXsmm() {
        return this.xsmm;
    }
    
    public void setXsmm(String xsmm) {
        this.xsmm = xsmm;
    }

    public Integer getYxbj() {
        return this.yxbj;
    }
    
    public void setYxbj(Integer yxbj) {
        this.yxbj = yxbj;
    }

    public String getBzxx() {
        return this.bzxx;
    }
    
    public void setBzxx(String bzxx) {
        this.bzxx = bzxx;
    }

    public Integer getSfdl() {
        return this.sfdl;
    }
    
    public void setSfdl(Integer sfdl) {
        this.sfdl = sfdl;
    }

    public String getZhdlsj() {
        return this.zhdlsj;
    }
    
    public void setZhdlsj(String zhdlsj) {
        this.zhdlsj = zhdlsj;
    }

    public String getZhsyrwmc() {
        return this.zhsyrwmc;
    }
    
    public void setZhsyrwmc(String zhsyrwmc) {
        this.zhsyrwmc = zhsyrwmc;
    }

    public Integer getSssysz() {
        return this.sssysz;
    }
    
    public void setSssysz(Integer sssysz) {
        this.sssysz = sssysz;
    }

    public Set getDjxxes() {
        return this.djxxes;
    }
    
    public void setDjxxes(Set djxxes) {
        this.djxxes = djxxes;
    }

	public Integer getSssyz() {
		return sssyz;
	}

	public void setSssyz(Integer sssyz) {
		this.sssyz = sssyz;
	}


	public Set getXsgwxxes() {
		return xsgwxxes;
	}


	public void setXsgwxxes(Set xsgwxxes) {
		this.xsgwxxes = xsgwxxes;
	}
}