package com.whjbsoft.www.po;

import java.util.HashSet;
import java.util.Set;


/**
 * Ygxx generated by MyEclipse - Hibernate Tools
 */

public class Ygxx  implements java.io.Serializable {


    // Fields    

     private Integer ygzj;
     private String ygbh;
     private String ygmc;
     private String ygzw;
     private String ygxb;
     private String csrq;
     private String gzrq;
     private String sfzh;
     private String ygdh;
     private String ygdz;
     private Double yggz;
     private String ygzt;
     private String ygms;
     private String ssbm;
     private String ssjg;
     private Integer ssxs;
     private Integer sssysz;
     private Set ccrydds = new HashSet(0);
     private Set ysrydds = new HashSet(0);


    // Constructors

    /** default constructor */
    public Ygxx() {
    }

    
    /** full constructor */
    public Ygxx(String ygbh, String ygmc, String ygzw, String ygxb, String csrq, String gzrq, String sfzh, String ygdh, String ygdz, Double yggz, String ygzt, String ygms, String ssjg, Integer ssxs, Integer sssysz, Set ccrydds, Set ysrydds) {
        this.ygbh = ygbh;
        this.ygmc = ygmc;
        this.ygzw = ygzw;
        this.ygxb = ygxb;
        this.csrq = csrq;
        this.gzrq = gzrq;
        this.sfzh = sfzh;
        this.ygdh = ygdh;
        this.ygdz = ygdz;
        this.yggz = yggz;
        this.ygzt = ygzt;
        this.ygms = ygms;
        this.ssjg = ssjg;
        this.ssxs = ssxs;
        this.sssysz = sssysz;
        this.ccrydds = ccrydds;
        this.ysrydds = ysrydds;
    }

   
    // Property accessors

    public Integer getYgzj() {
        return this.ygzj;
    }
    
    public void setYgzj(Integer ygzj) {
        this.ygzj = ygzj;
    }

    public String getYgbh() {
        return this.ygbh;
    }
    
    public void setYgbh(String ygbh) {
        this.ygbh = ygbh;
    }

    public String getYgmc() {
        return this.ygmc;
    }
    
    public void setYgmc(String ygmc) {
        this.ygmc = ygmc;
    }

    public String getYgzw() {
        return this.ygzw;
    }
    
    public void setYgzw(String ygzw) {
        this.ygzw = ygzw;
    }

    public String getYgxb() {
        return this.ygxb;
    }
    
    public void setYgxb(String ygxb) {
        this.ygxb = ygxb;
    }

    public String getCsrq() {
        return this.csrq;
    }
    
    public void setCsrq(String csrq) {
        this.csrq = csrq;
    }

    public String getGzrq() {
        return this.gzrq;
    }
    
    public void setGzrq(String gzrq) {
        this.gzrq = gzrq;
    }

    public String getSfzh() {
        return this.sfzh;
    }
    
    public void setSfzh(String sfzh) {
        this.sfzh = sfzh;
    }

    public String getYgdh() {
        return this.ygdh;
    }
    
    public void setYgdh(String ygdh) {
        this.ygdh = ygdh;
    }

    public String getYgdz() {
        return this.ygdz;
    }
    
    public void setYgdz(String ygdz) {
        this.ygdz = ygdz;
    }

    public Double getYggz() {
        return this.yggz;
    }
    
    public void setYggz(Double yggz) {
        this.yggz = yggz;
    }

    public String getYgzt() {
        return this.ygzt;
    }
    
    public void setYgzt(String ygzt) {
        this.ygzt = ygzt;
    }

    public String getYgms() {
        return this.ygms;
    }
    
    public void setYgms(String ygms) {
        this.ygms = ygms;
    }

    public String getSsjg() {
        return this.ssjg;
    }
    
    public void setSsjg(String ssjg) {
        this.ssjg = ssjg;
    }

    public Integer getSsxs() {
        return this.ssxs;
    }
    
    public void setSsxs(Integer ssxs) {
        this.ssxs = ssxs;
    }

    public Integer getSssysz() {
        return this.sssysz;
    }
    
    public void setSssysz(Integer sssysz) {
        this.sssysz = sssysz;
    }

    public Set getCcrydds() {
        return this.ccrydds;
    }
    
    public void setCcrydds(Set ccrydds) {
        this.ccrydds = ccrydds;
    }

    public Set getYsrydds() {
        return this.ysrydds;
    }
    
    public void setYsrydds(Set ysrydds) {
        this.ysrydds = ysrydds;
    }


	public String getSsbm() {
		return ssbm;
	}


	public void setSsbm(String ssbm) {
		this.ssbm = ssbm;
	}
    
}