package com.whjbsoft.www.po;

import java.util.HashSet;
import java.util.Set;


/**
 * Ykdd generated by MyEclipse - Hibernate Tools
 */

public class Ykdd  implements java.io.Serializable {


    // Fields    

     private Integer ykzj;
     private String ykbh;
     private String ddrq;
     private Integer ckkfzj;
     private String ckkfmc;
     private Integer rkkfzj;
     private String rkkfmc;
     private String ckczr;
     private String rkczr;
     private String tdr;
     private String tdsj;
     private Integer ykzt;
     private String bzxx;
     private Integer ssxs;
     private Integer sssysz;
     private Set ykmxes = new HashSet(0);


    // Constructors

    /** default constructor */
    public Ykdd() {
    }

    
    /** full constructor */
    public Ykdd(String ykbh, String ddrq, Integer ckkfzj, String ckkfmc, Integer rkkfzj, String rkkfmc, String ckczr, String rkczr, String tdr, String tdsj, Integer ykzt, String bzxx, Integer ssxs, Integer sssysz, Set ykmxes) {
        this.ykbh = ykbh;
        this.ddrq = ddrq;
        this.ckkfzj = ckkfzj;
        this.ckkfmc = ckkfmc;
        this.rkkfzj = rkkfzj;
        this.rkkfmc = rkkfmc;
        this.ckczr = ckczr;
        this.rkczr = rkczr;
        this.tdr = tdr;
        this.tdsj = tdsj;
        this.ykzt = ykzt;
        this.bzxx = bzxx;
        this.ssxs = ssxs;
        this.sssysz = sssysz;
        this.ykmxes = ykmxes;
    }

   
    // Property accessors

    public Integer getYkzj() {
        return this.ykzj;
    }
    
    public void setYkzj(Integer ykzj) {
        this.ykzj = ykzj;
    }

    public String getYkbh() {
        return this.ykbh;
    }
    
    public void setYkbh(String ykbh) {
        this.ykbh = ykbh;
    }

    public String getDdrq() {
        return this.ddrq;
    }
    
    public void setDdrq(String ddrq) {
        this.ddrq = ddrq;
    }

    public Integer getCkkfzj() {
        return this.ckkfzj;
    }
    
    public void setCkkfzj(Integer ckkfzj) {
        this.ckkfzj = ckkfzj;
    }

    public String getCkkfmc() {
        return this.ckkfmc;
    }
    
    public void setCkkfmc(String ckkfmc) {
        this.ckkfmc = ckkfmc;
    }

    public Integer getRkkfzj() {
        return this.rkkfzj;
    }
    
    public void setRkkfzj(Integer rkkfzj) {
        this.rkkfzj = rkkfzj;
    }

    public String getRkkfmc() {
        return this.rkkfmc;
    }
    
    public void setRkkfmc(String rkkfmc) {
        this.rkkfmc = rkkfmc;
    }

    public String getCkczr() {
        return this.ckczr;
    }
    
    public void setCkczr(String ckczr) {
        this.ckczr = ckczr;
    }

    public String getRkczr() {
        return this.rkczr;
    }
    
    public void setRkczr(String rkczr) {
        this.rkczr = rkczr;
    }

    public String getTdr() {
        return this.tdr;
    }
    
    public void setTdr(String tdr) {
        this.tdr = tdr;
    }

    public String getTdsj() {
        return this.tdsj;
    }
    
    public void setTdsj(String tdsj) {
        this.tdsj = tdsj;
    }

    public Integer getYkzt() {
        return this.ykzt;
    }
    
    public void setYkzt(Integer ykzt) {
        this.ykzt = ykzt;
    }

    public String getBzxx() {
        return this.bzxx;
    }
    
    public void setBzxx(String bzxx) {
        this.bzxx = bzxx;
    }

    public Integer getSsxs() {
        return this.ssxs;
    }
    
    public void setSsxs(Integer ssxs) {
        this.ssxs = ssxs;
    }

    public Integer getSssysz() {
        return this.sssysz;
    }
    
    public void setSssysz(Integer sssysz) {
        this.sssysz = sssysz;
    }

    public Set getYkmxes() {
        return this.ykmxes;
    }
    
    public void setYkmxes(Set ykmxes) {
        this.ykmxes = ykmxes;
    }
   








}