package com.whjbsoft.www.po;



/**
 * YsryddId generated by MyEclipse - Hibernate Tools
 */

public class YsryddId  implements java.io.Serializable {


    // Fields    

     private Integer ysddzj;
     private Integer ygzj;


    // Constructors

    /** default constructor */
    public YsryddId() {
    }

    
    /** full constructor */
    public YsryddId(Integer ysddzj, Integer ygzj) {
        this.ysddzj = ysddzj;
        this.ygzj = ygzj;
    }

   
    // Property accessors

    public Integer getYsddzj() {
        return this.ysddzj;
    }
    
    public void setYsddzj(Integer ysddzj) {
        this.ysddzj = ysddzj;
    }

    public Integer getYgzj() {
        return this.ygzj;
    }
    
    public void setYgzj(Integer ygzj) {
        this.ygzj = ygzj;
    }
   



   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof YsryddId) ) return false;
		 YsryddId castOther = ( YsryddId ) other; 
         
		 return ( (this.getYsddzj()==castOther.getYsddzj()) || ( this.getYsddzj()!=null && castOther.getYsddzj()!=null && this.getYsddzj().equals(castOther.getYsddzj()) ) )
 && ( (this.getYgzj()==castOther.getYgzj()) || ( this.getYgzj()!=null && castOther.getYgzj()!=null && this.getYgzj().equals(castOther.getYgzj()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getYsddzj() == null ? 0 : this.getYsddzj().hashCode() );
         result = 37 * result + ( getYgzj() == null ? 0 : this.getYgzj().hashCode() );
         return result;
   }   





}