package com.whjbsoft.www.exam.po;



/**
 * Sjkt generated by MyEclipse - Hibernate Tools
 */

public class Sjkts  implements java.io.Serializable {


    // Fields    

     private SjktsId id;


    public Sjkts() {
    }

    public Sjkts(SjktsId id) {
		this.id = id;
	}

	public SjktsId getId() {
        return this.id;
    }
    
    public void setId(SjktsId id) {
        this.id = id;
    }
}