package com.whjbsoft.www.exam.po;

/**
 * SjktId generated by MyEclipse - Hibernate Tools
 */

public class SjktsId implements java.io.Serializable {

	// Fields    

	private Stgls stgl;
	private Sjtxs sjtx;

	// Constructors

	/** default constructor */
	public SjktsId() {
	}

	/** full constructor */
	public SjktsId(Stgls stgl, Sjtxs sjtx) {
		this.stgl = stgl;
		this.sjtx = sjtx;
	}

	// Property accessors

	public Stgls getStgl() {
		return this.stgl;
	}

	public void setStgl(Stgls stgl) {
		this.stgl = stgl;
	}

	public Sjtxs getSjtx() {
		return this.sjtx;
	}

	public void setSjtx(Sjtxs sjtx) {
		this.sjtx = sjtx;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof SjktsId))
			return false;
		SjktsId castOther = (SjktsId) other;

		return ((this.getStgl() == castOther.getStgl()) || (this.getStgl() != null
				&& castOther.getStgl() != null && this.getStgl().equals(
				castOther.getStgl())))
				&& ((this.getSjtx() == castOther.getSjtx()) || (this.getSjtx() != null
						&& castOther.getSjtx() != null && this.getSjtx()
						.equals(castOther.getSjtx())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getStgl() == null ? 0 : this.getStgl().hashCode());
		result = 37 * result
				+ (getSjtx() == null ? 0 : this.getSjtx().hashCode());
		return result;
	}

}