package com.whjbsoft.www.exam.po;

import java.util.HashSet;
import java.util.Set;


/**
 * Sjtx generated by MyEclipse - Hibernate Tools
 */

public class Sjtxs  implements java.io.Serializable {


    // Fields    
     private Integer sjtxzj;
     private Sjxxs sjxx;
     private String sjtxmc;
     private Integer zts;
     private Integer dtfs;
     private Integer zjfs;
     private Integer plsx;
     private Set sjkts = new HashSet(0);


    // Constructors

    /** default constructor */
    public Sjtxs() {
    }

	/** minimal constructor */
    public Sjtxs(Sjxxs sjxx) {
        this.sjxx = sjxx;
    }
    
    /** full constructor */
    public Sjtxs(Sjxxs sjxx, String sjtxmc, Integer zts, Integer dtfs, Integer zjfs, Set sjkts) {
        this.sjxx = sjxx;
        this.sjtxmc = sjtxmc;
        this.zts = zts;
        this.dtfs = dtfs;
        this.zjfs = zjfs;
        this.sjkts = sjkts;
    }   

    public Integer getSjtxzj() {
		return sjtxzj;
	}

	public void setSjtxzj(Integer sjtxzj) {
		this.sjtxzj = sjtxzj;
	}

	public Sjxxs getSjxx() {
        return this.sjxx;
    }
    
    public void setSjxx(Sjxxs sjxx) {
        this.sjxx = sjxx;
    }

    public String getSjtxmc() {
        return this.sjtxmc;
    }
    
    public void setSjtxmc(String sjtxmc) {
        this.sjtxmc = sjtxmc;
    }

    public Integer getZts() {
        return this.zts;
    }
    
    public void setZts(Integer zts) {
        this.zts = zts;
    }

    public Integer getDtfs() {
        return this.dtfs;
    }
    
    public void setDtfs(Integer dtfs) {
        this.dtfs = dtfs;
    }

    public Integer getZjfs() {
        return this.zjfs;
    }
    
    public void setZjfs(Integer zjfs) {
        this.zjfs = zjfs;
    }

    public Set getSjkts() {
        return this.sjkts;
    }
    
    public void setSjkts(Set sjkts) {
        this.sjkts = sjkts;
    }

	public Integer getPlsx() {
		return plsx;
	}

	public void setPlsx(Integer plsx) {
		this.plsx = plsx;
	}
}