package com.whjbsoft.www.po;

import java.util.HashSet;
import java.util.Set;


/**
 * Bxxx generated by MyEclipse - Hibernate Tools
 */

public class Bxxx  implements java.io.Serializable {


    // Fields    

     private Integer bxzj;
     private String bxbh;
     private String bxms;
     private Integer ssxs;
     private Integer sssysz;
     private String sfz;
     private String mdz;
     private Set xlyhs = new HashSet(0);
     private Set bxlcs = new HashSet(0);


    // Constructors

    /** default constructor */
    public Bxxx() {
    }

    
    /** full constructor */
    public Bxxx(String bxbh, String bxms, Integer ssxs, Integer sssysz, String sfz, String mdz, Set xlyhs, Set bxlcs) {
        this.bxbh = bxbh;
        this.bxms = bxms;
        this.ssxs = ssxs;
        this.sssysz = sssysz;
        this.sfz = sfz;
        this.mdz = mdz;
        this.xlyhs = xlyhs;
        this.bxlcs = bxlcs;
    }

   
    // Property accessors

    public Integer getBxzj() {
        return this.bxzj;
    }
    
    public void setBxzj(Integer bxzj) {
        this.bxzj = bxzj;
    }

    public String getBxbh() {
        return this.bxbh;
    }
    
    public void setBxbh(String bxbh) {
        this.bxbh = bxbh;
    }

    public String getBxms() {
        return this.bxms;
    }
    
    public void setBxms(String bxms) {
        this.bxms = bxms;
    }

    public Integer getSsxs() {
        return this.ssxs;
    }
    
    public void setSsxs(Integer ssxs) {
        this.ssxs = ssxs;
    }

    public Integer getSssysz() {
        return this.sssysz;
    }
    
    public void setSssysz(Integer sssysz) {
        this.sssysz = sssysz;
    }

    public String getSfz() {
        return this.sfz;
    }
    
    public void setSfz(String sfz) {
        this.sfz = sfz;
    }

    public String getMdz() {
        return this.mdz;
    }
    
    public void setMdz(String mdz) {
        this.mdz = mdz;
    }

    public Set getXlyhs() {
        return this.xlyhs;
    }
    
    public void setXlyhs(Set xlyhs) {
        this.xlyhs = xlyhs;
    }

    public Set getBxlcs() {
        return this.bxlcs;
    }
    
    public void setBxlcs(Set bxlcs) {
        this.bxlcs = bxlcs;
    }
   








}