package com.whjbsoft.www.po;



/**
 * CcsbddId generated by MyEclipse - Hibernate Tools
 */

public class CcsbddId  implements java.io.Serializable {


    // Fields    

     private Integer crkzj;
     private Integer sbzj;


    // Constructors

    /** default constructor */
    public CcsbddId() {
    }

    
    /** full constructor */
    public CcsbddId(Integer crkzj, Integer sbzj) {
        this.crkzj = crkzj;
        this.sbzj = sbzj;
    }

   
    // Property accessors

    public Integer getCrkzj() {
        return this.crkzj;
    }
    
    public void setCrkzj(Integer crkzj) {
        this.crkzj = crkzj;
    }

    public Integer getSbzj() {
        return this.sbzj;
    }
    
    public void setSbzj(Integer sbzj) {
        this.sbzj = sbzj;
    }
   



   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof CcsbddId) ) return false;
		 CcsbddId castOther = ( CcsbddId ) other; 
         
		 return ( (this.getCrkzj()==castOther.getCrkzj()) || ( this.getCrkzj()!=null && castOther.getCrkzj()!=null && this.getCrkzj().equals(castOther.getCrkzj()) ) )
 && ( (this.getSbzj()==castOther.getSbzj()) || ( this.getSbzj()!=null && castOther.getSbzj()!=null && this.getSbzj().equals(castOther.getSbzj()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getCrkzj() == null ? 0 : this.getCrkzj().hashCode() );
         result = 37 * result + ( getSbzj() == null ? 0 : this.getSbzj().hashCode() );
         return result;
   }   





}