package com.whjbsoft.www.po;



/**
 * Ccsbdd generated by MyEclipse - Hibernate Tools
 */

public class Ccsbdd  implements java.io.Serializable {


    // Fields    

     private CcsbddId id;
     private Sbxx sbxx;
     private Crkdd crkdd;


    // Constructors

    /** default constructor */
    public Ccsbdd() {
    }

    
    /** full constructor */
    public Ccsbdd(Sbxx sbxx, Crkdd crkdd) {
        this.sbxx = sbxx;
        this.crkdd = crkdd;
    }

   
    // Property accessors

    public CcsbddId getId() {
        return this.id;
    }
    
    public void setId(CcsbddId id) {
        this.id = id;
    }

    public Sbxx getSbxx() {
        return this.sbxx;
    }
    
    public void setSbxx(Sbxx sbxx) {
        this.sbxx = sbxx;
    }

    public Crkdd getCrkdd() {
        return this.crkdd;
    }
    
    public void setCrkdd(Crkdd crkdd) {
        this.crkdd = crkdd;
    }
   








}