package com.whjbsoft.www.po;

import java.util.HashSet;
import java.util.Set;


/**
 * Crkdd generated by MyEclipse - Hibernate Tools
 */

public class Crkdd  implements java.io.Serializable {


    // Fields    

     private Integer crkzj;
     private Khht khht;
     private String ddbh;
     private String khzlh;
     private String ddlx;
     private String jjcd;
     private String xdsj;
     private Integer ddzt;
     private String crklx;
     private String crkfs;
     private Integer sykfzj;
     private String kfmc;
     private String yjcrksj;
     private String bzxx;
     private String zjbh;
     private String zjr;
     private String zjsj;
     private String sjcrksj;
     private Integer ssxs;
     private Integer sssysz;
     private Set crkhps = new HashSet(0);
     private Set ccsbdds = new HashSet(0);
     private Set ccrydds = new HashSet(0);


    // Constructors

    /** default constructor */
    public Crkdd() {
    }

    
    /** full constructor */
    public Crkdd(Khht khht, String ddbh, String khzlh, String ddlx, String jjcd, String xdsj, Integer ddzt, String crklx, String crkfs, Integer sykfzj, String kfmc, String yjcrksj, String bzxx, String zjbh, String zjr, String zjsj, Integer ssxs, Integer sssysz, Set crkhps, Set ccsbdds, Set ccrydds) {
        this.khht = khht;
        this.ddbh = ddbh;
        this.khzlh = khzlh;
        this.ddlx = ddlx;
        this.jjcd = jjcd;
        this.xdsj = xdsj;
        this.ddzt = ddzt;
        this.crklx = crklx;
        this.crkfs = crkfs;
        this.sykfzj = sykfzj;
        this.kfmc = kfmc;
        this.yjcrksj = yjcrksj;
        this.bzxx = bzxx;
        this.zjbh = zjbh;
        this.zjr = zjr;
        this.zjsj = zjsj;
        this.ssxs = ssxs;
        this.sssysz = sssysz;
        this.crkhps = crkhps;
        this.ccsbdds = ccsbdds;
        this.ccrydds = ccrydds;
    }

   
    // Property accessors

    public Integer getCrkzj() {
        return this.crkzj;
    }
    
    public void setCrkzj(Integer crkzj) {
        this.crkzj = crkzj;
    }

    public Khht getKhht() {
        return this.khht;
    }
    
    public void setKhht(Khht khht) {
        this.khht = khht;
    }

    public String getDdbh() {
        return this.ddbh;
    }
    
    public void setDdbh(String ddbh) {
        this.ddbh = ddbh;
    }

    public String getKhzlh() {
        return this.khzlh;
    }
    
    public void setKhzlh(String khzlh) {
        this.khzlh = khzlh;
    }

    public String getDdlx() {
        return this.ddlx;
    }
    
    public void setDdlx(String ddlx) {
        this.ddlx = ddlx;
    }

    public String getJjcd() {
        return this.jjcd;
    }
    
    public void setJjcd(String jjcd) {
        this.jjcd = jjcd;
    }

    public String getXdsj() {
        return this.xdsj;
    }
    
    public void setXdsj(String xdsj) {
        this.xdsj = xdsj;
    }

    public Integer getDdzt() {
        return this.ddzt;
    }
    
    public void setDdzt(Integer ddzt) {
        this.ddzt = ddzt;
    }

    public String getCrklx() {
        return this.crklx;
    }
    
    public void setCrklx(String crklx) {
        this.crklx = crklx;
    }

    public String getCrkfs() {
        return this.crkfs;
    }
    
    public void setCrkfs(String crkfs) {
        this.crkfs = crkfs;
    }

    public Integer getSykfzj() {
        return this.sykfzj;
    }
    
    public void setSykfzj(Integer sykfzj) {
        this.sykfzj = sykfzj;
    }

    public String getKfmc() {
        return this.kfmc;
    }
    
    public void setKfmc(String kfmc) {
        this.kfmc = kfmc;
    }

    public String getYjcrksj() {
        return this.yjcrksj;
    }
    
    public void setYjcrksj(String yjcrksj) {
        this.yjcrksj = yjcrksj;
    }

    public String getBzxx() {
        return this.bzxx;
    }
    
    public void setBzxx(String bzxx) {
        this.bzxx = bzxx;
    }

    public String getZjbh() {
        return this.zjbh;
    }
    
    public void setZjbh(String zjbh) {
        this.zjbh = zjbh;
    }

    public String getZjr() {
        return this.zjr;
    }
    
    public void setZjr(String zjr) {
        this.zjr = zjr;
    }

    public String getZjsj() {
        return this.zjsj;
    }
    
    public void setZjsj(String zjsj) {
        this.zjsj = zjsj;
    }

    public Integer getSsxs() {
        return this.ssxs;
    }
    
    public void setSsxs(Integer ssxs) {
        this.ssxs = ssxs;
    }

    public Integer getSssysz() {
        return this.sssysz;
    }
    
    public void setSssysz(Integer sssysz) {
        this.sssysz = sssysz;
    }

    public Set getCrkhps() {
        return this.crkhps;
    }
    
    public void setCrkhps(Set crkhps) {
        this.crkhps = crkhps;
    }

    public Set getCcsbdds() {
        return this.ccsbdds;
    }
    
    public void setCcsbdds(Set ccsbdds) {
        this.ccsbdds = ccsbdds;
    }

    public Set getCcrydds() {
        return this.ccrydds;
    }
    
    public void setCcrydds(Set ccrydds) {
        this.ccrydds = ccrydds;
    }

	public String getSjcrksj() {
		return sjcrksj;
	}

	public void setSjcrksj(String sjcrksj) {
		this.sjcrksj = sjcrksj;
	}
}