package com.whjbsoft.www.po;

import java.util.HashSet;
import java.util.Set;


/**
 * Cwxx generated by MyEclipse - Hibernate Tools
 */

public class Cwxx  implements java.io.Serializable {


    // Fields    

     private Integer cwzj;
     private Qwxx qwxx;    
     private String cwbh;
     private String cwtm;
     private String cwzfm;
     private Double cwsx;
     private Double hgsl;
     private Double shsl;
     private String hpbm;
     private String hpmc;
     private String hpdw;
     private Set ykmxesForCwzj = new HashSet(0);
     private Set ykmxesForCwxCwzj = new HashSet(0);
     private Set crkhps = new HashSet(0);


    // Constructors

    /** default constructor */
    public Cwxx() {
    }

   
    // Property accessors

    public Integer getCwzj() {
        return this.cwzj;
    }
    
    public void setCwzj(Integer cwzj) {
        this.cwzj = cwzj;
    }

    public Qwxx getQwxx() {
        return this.qwxx;
    }
    
    public void setQwxx(Qwxx qwxx) {
        this.qwxx = qwxx;
    }
    public String getCwbh() {
        return this.cwbh;
    }
    
    public void setCwbh(String cwbh) {
        this.cwbh = cwbh;
    }

    public String getCwtm() {
        return this.cwtm;
    }
    
    public void setCwtm(String cwtm) {
        this.cwtm = cwtm;
    }

    public String getCwzfm() {
        return this.cwzfm;
    }
    
    public void setCwzfm(String cwzfm) {
        this.cwzfm = cwzfm;
    }

    public Double getCwsx() {
        return this.cwsx;
    }
    
    public void setCwsx(Double cwsx) {
        this.cwsx = cwsx;
    }

    public Double getHgsl() {
        return this.hgsl;
    }
    
    public void setHgsl(Double hgsl) {
        this.hgsl = hgsl;
    }

    public Double getShsl() {
        return this.shsl;
    }
    
    public void setShsl(Double shsl) {
        this.shsl = shsl;
    }

    public String getHpbm() {
        return this.hpbm;
    }
    
    public void setHpbm(String hpbm) {
        this.hpbm = hpbm;
    }

    public String getHpmc() {
        return this.hpmc;
    }
    
    public void setHpmc(String hpmc) {
        this.hpmc = hpmc;
    }

    public String getHpdw() {
        return this.hpdw;
    }
    
    public void setHpdw(String hpdw) {
        this.hpdw = hpdw;
    }

    public Set getYkmxesForCwzj() {
        return this.ykmxesForCwzj;
    }
    
    public void setYkmxesForCwzj(Set ykmxesForCwzj) {
        this.ykmxesForCwzj = ykmxesForCwzj;
    }

    public Set getYkmxesForCwxCwzj() {
        return this.ykmxesForCwxCwzj;
    }
    
    public void setYkmxesForCwxCwzj(Set ykmxesForCwxCwzj) {
        this.ykmxesForCwxCwzj = ykmxesForCwxCwzj;
    }

	public Set getCrkhps() {
		return crkhps;
	}

	public void setCrkhps(Set crkhps) {
		this.crkhps = crkhps;
	}

}