package com.whjbsoft.www.po;

import java.util.HashSet;
import java.util.Set;


/**
 * Djxx generated by MyEclipse - Hibernate Tools
 */

public class Djxx  implements java.io.Serializable {


    // Fields    

     private Integer djzj;
     private Sjxx sjxx;
     private Xsxx xsxx;
     private String djsj;
     private Integer djjxsj;
     private Integer sfjj;
     private Double sjdf;
     private Set dtxxes = new HashSet(0);


    // Constructors

    /** default constructor */
    public Djxx() {
    }

    
    /** full constructor */
    public Djxx(Sjxx sjxx, Xsxx xsxx, String djsj, Integer djjxsj, Integer sfjj, Double sjdf, Set dtxxes) {
        this.sjxx = sjxx;
        this.xsxx = xsxx;
        this.djsj = djsj;
        this.djjxsj = djjxsj;
        this.sfjj = sfjj;
        this.sjdf = sjdf;
        this.dtxxes = dtxxes;
    }

   
    // Property accessors

    public Integer getDjzj() {
        return this.djzj;
    }
    
    public void setDjzj(Integer djzj) {
        this.djzj = djzj;
    }

    public Sjxx getSjxx() {
        return this.sjxx;
    }
    
    public void setSjxx(Sjxx sjxx) {
        this.sjxx = sjxx;
    }

    public Xsxx getXsxx() {
        return this.xsxx;
    }
    
    public void setXsxx(Xsxx xsxx) {
        this.xsxx = xsxx;
    }

    public String getDjsj() {
        return this.djsj;
    }
    
    public void setDjsj(String djsj) {
        this.djsj = djsj;
    }

    public Integer getDjjxsj() {
        return this.djjxsj;
    }
    
    public void setDjjxsj(Integer djjxsj) {
        this.djjxsj = djjxsj;
    }

    public Integer getSfjj() {
        return this.sfjj;
    }
    
    public void setSfjj(Integer sfjj) {
        this.sfjj = sfjj;
    }

    public Double getSjdf() {
        return this.sjdf;
    }
    
    public void setSjdf(Double sjdf) {
        this.sjdf = sjdf;
    }

    public Set getDtxxes() {
        return this.dtxxes;
    }
    
    public void setDtxxes(Set dtxxes) {
        this.dtxxes = dtxxes;
    }
   








}