package com.whjbsoft.www.po;



/**
 * Dtxx generated by MyEclipse - Hibernate Tools
 */

public class Dtxx  implements java.io.Serializable {


    // Fields    

     private Integer dtzj;
     private Djxx djxx;
     private Integer ktzj;
     private Integer ktfs;
     private Double dtfs;
     private Integer yyksl;
     private Integer syksl;
     private Integer sfdt;


    // Constructors

    /** default constructor */
    public Dtxx() {
    }

    
    /** full constructor */
    public Dtxx(Djxx djxx, Integer ktzj, Integer ktfs, Double dtfs, Integer yyksl, Integer syksl, Integer sfdt) {
        this.djxx = djxx;
        this.ktzj = ktzj;
        this.ktfs = ktfs;
        this.dtfs = dtfs;
        this.yyksl = yyksl;
        this.syksl = syksl;
        this.sfdt = sfdt;
    }

   
    // Property accessors

    public Integer getDtzj() {
        return this.dtzj;
    }
    
    public void setDtzj(Integer dtzj) {
        this.dtzj = dtzj;
    }

    public Djxx getDjxx() {
        return this.djxx;
    }
    
    public void setDjxx(Djxx djxx) {
        this.djxx = djxx;
    }

    public Integer getKtzj() {
        return this.ktzj;
    }
    
    public void setKtzj(Integer ktzj) {
        this.ktzj = ktzj;
    }

    public Integer getKtfs() {
        return this.ktfs;
    }
    
    public void setKtfs(Integer ktfs) {
        this.ktfs = ktfs;
    }

    public Double getDtfs() {
        return this.dtfs;
    }
    
    public void setDtfs(Double dtfs) {
        this.dtfs = dtfs;
    }

    public Integer getYyksl() {
        return this.yyksl;
    }
    
    public void setYyksl(Integer yyksl) {
        this.yyksl = yyksl;
    }

    public Integer getSyksl() {
        return this.syksl;
    }
    
    public void setSyksl(Integer syksl) {
        this.syksl = syksl;
    }

    public Integer getSfdt() {
        return this.sfdt;
    }
    
    public void setSfdt(Integer sfdt) {
        this.sfdt = sfdt;
    }
   








}