package com.whjbsoft.www.po;



/**
 * Hpxx generated by MyEclipse - Hibernate Tools
 */

public class Hpxx  implements java.io.Serializable {


    // Fields    

     private Integer hpzj;
     private String hpbm;
     private String hpmc;
     private String txm;
     private String pym;
     private String hpdw;
     private String hplx;
     private String hpzlx;
     private String hpgg;
     private String hpxh;
     private String sccs;
     private Double hptj;
     private String tjdw;
     private String bzq;
     private Double zl;
     private String zldw;
     private String cchj;
     private String hpsx;
     private Integer ssxs;
     private Integer sssysz;
     private String hpsm;
     private Double hpdj;


    // Constructors

    /** default constructor */
    public Hpxx() {
    }

    
    /** full constructor */
    public Hpxx(String hpbm, String hpmc, String txm, String pym, String hpdw, String hplx, String hpzlx, String hpgg, String hpxh, String sccs, Double hptj, String bzq, Double zl, String cchj, String hpsx, Integer ssxs, Integer sssysz, String hpsm, Double hpdj) {
        this.hpbm = hpbm;
        this.hpmc = hpmc;
        this.txm = txm;
        this.pym = pym;
        this.hpdw = hpdw;
        this.hplx = hplx;
        this.hpzlx = hpzlx;
        this.hpgg = hpgg;
        this.hpxh = hpxh;
        this.sccs = sccs;
        this.hptj = hptj;
        this.bzq = bzq;
        this.zl = zl;
        this.cchj = cchj;
        this.hpsx = hpsx;
        this.ssxs = ssxs;
        this.sssysz = sssysz;
        this.hpsm = hpsm;
        this.hpdj = hpdj;
    }

   
    // Property accessors

    public Integer getHpzj() {
        return this.hpzj;
    }
    
    public void setHpzj(Integer hpzj) {
        this.hpzj = hpzj;
    }

    public String getHpbm() {
        return this.hpbm;
    }
    
    public void setHpbm(String hpbm) {
        this.hpbm = hpbm;
    }

    public String getHpmc() {
        return this.hpmc;
    }
    
    public void setHpmc(String hpmc) {
        this.hpmc = hpmc;
    }

    public String getTxm() {
        return this.txm;
    }
    
    public void setTxm(String txm) {
        this.txm = txm;
    }

    public String getPym() {
        return this.pym;
    }
    
    public void setPym(String pym) {
        this.pym = pym;
    }

    public String getHpdw() {
        return this.hpdw;
    }
    
    public void setHpdw(String hpdw) {
        this.hpdw = hpdw;
    }

    public String getHplx() {
        return this.hplx;
    }
    
    public void setHplx(String hplx) {
        this.hplx = hplx;
    }

    public String getHpzlx() {
        return this.hpzlx;
    }
    
    public void setHpzlx(String hpzlx) {
        this.hpzlx = hpzlx;
    }

    public String getHpgg() {
        return this.hpgg;
    }
    
    public void setHpgg(String hpgg) {
        this.hpgg = hpgg;
    }

    public String getHpxh() {
        return this.hpxh;
    }
    
    public void setHpxh(String hpxh) {
        this.hpxh = hpxh;
    }

    public String getSccs() {
        return this.sccs;
    }
    
    public void setSccs(String sccs) {
        this.sccs = sccs;
    }

    public Double getHptj() {
        return this.hptj;
    }
    
    public void setHptj(Double hptj) {
        this.hptj = hptj;
    }

    public String getBzq() {
        return this.bzq;
    }
    
    public void setBzq(String bzq) {
        this.bzq = bzq;
    }

    public Double getZl() {
        return this.zl;
    }
    
    public void setZl(Double zl) {
        this.zl = zl;
    }

    public String getCchj() {
        return this.cchj;
    }
    
    public void setCchj(String cchj) {
        this.cchj = cchj;
    }

    public String getHpsx() {
        return this.hpsx;
    }
    
    public void setHpsx(String hpsx) {
        this.hpsx = hpsx;
    }

    public Integer getSsxs() {
        return this.ssxs;
    }
    
    public void setSsxs(Integer ssxs) {
        this.ssxs = ssxs;
    }

    public Integer getSssysz() {
        return this.sssysz;
    }
    
    public void setSssysz(Integer sssysz) {
        this.sssysz = sssysz;
    }

    public String getHpsm() {
        return this.hpsm;
    }
    
    public void setHpsm(String hpsm) {
        this.hpsm = hpsm;
    }

    public Double getHpdj() {
        return this.hpdj;
    }
    
    public void setHpdj(Double hpdj) {
        this.hpdj = hpdj;
    }

	public String getTjdw() {
		return tjdw;
	}

	public void setTjdw(String tjdw) {
		this.tjdw = tjdw;
	}

	public String getZldw() {
		return zldw;
	}
	public void setZldw(String zldw) {
		this.zldw = zldw;
	}
}