package com.whjbsoft.www.po;



/**
 * JsbjId generated by MyEclipse - Hibernate Tools
 */

public class JsbjId  implements java.io.Serializable {


    // Fields    

     private Integer jxzj;
     private Integer bjzj;


    // Constructors

    /** default constructor */
    public JsbjId() {
    }

    
    /** full constructor */
    public JsbjId(Integer jxzj, Integer bjzj) {
        this.jxzj = jxzj;
        this.bjzj = bjzj;
    }

   
    // Property accessors

    public Integer getJxzj() {
        return this.jxzj;
    }
    
    public void setJxzj(Integer jxzj) {
        this.jxzj = jxzj;
    }

    public Integer getBjzj() {
        return this.bjzj;
    }
    
    public void setBjzj(Integer bjzj) {
        this.bjzj = bjzj;
    }
   



   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof JsbjId) ) return false;
		 JsbjId castOther = ( JsbjId ) other; 
         
		 return ( (this.getJxzj()==castOther.getJxzj()) || ( this.getJxzj()!=null && castOther.getJxzj()!=null && this.getJxzj().equals(castOther.getJxzj()) ) )
 && ( (this.getBjzj()==castOther.getBjzj()) || ( this.getBjzj()!=null && castOther.getBjzj()!=null && this.getBjzj().equals(castOther.getBjzj()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getJxzj() == null ? 0 : this.getJxzj().hashCode() );
         result = 37 * result + ( getBjzj() == null ? 0 : this.getBjzj().hashCode() );
         return result;
   }   





}