package com.whjbsoft.www.po;

import java.util.HashSet;
import java.util.Set;


/**
 * Jsgl generated by MyEclipse - Hibernate Tools
 */

public class Jsgl  implements java.io.Serializable {


    // Fields    

     private Integer jxzj;
     private String jsbh;
     private String jsmc;
     private String jsmm;
     private String bzxx;
     private Integer jslx;
     private Integer kfxg;
     private Set jsbjs = new HashSet(0);


    // Constructors

    /** default constructor */
    public Jsgl() {
    }

    
    /** full constructor */
    public Jsgl(String jsbh, String jsmc, String jsmm, String bzxx, Integer jslx, Integer kfxg, Set jsbjs) {
        this.jsbh = jsbh;
        this.jsmc = jsmc;
        this.jsmm = jsmm;
        this.bzxx = bzxx;
        this.jslx = jslx;
        this.kfxg = kfxg;
        this.jsbjs = jsbjs;
    }

   
    // Property accessors

    public Integer getJxzj() {
        return this.jxzj;
    }
    
    public void setJxzj(Integer jxzj) {
        this.jxzj = jxzj;
    }

    public String getJsbh() {
        return this.jsbh;
    }
    
    public void setJsbh(String jsbh) {
        this.jsbh = jsbh;
    }

    public String getJsmc() {
        return this.jsmc;
    }
    
    public void setJsmc(String jsmc) {
        this.jsmc = jsmc;
    }

    public String getJsmm() {
        return this.jsmm;
    }
    
    public void setJsmm(String jsmm) {
        this.jsmm = jsmm;
    }

    public String getBzxx() {
        return this.bzxx;
    }
    
    public void setBzxx(String bzxx) {
        this.bzxx = bzxx;
    }

    public Integer getJslx() {
        return this.jslx;
    }
    
    public void setJslx(Integer jslx) {
        this.jslx = jslx;
    }

    public Integer getKfxg() {
        return this.kfxg;
    }
    
    public void setKfxg(Integer kfxg) {
        this.kfxg = kfxg;
    }

    public Set getJsbjs() {
        return this.jsbjs;
    }
    
    public void setJsbjs(Set jsbjs) {
        this.jsbjs = jsbjs;
    }
   








}