package com.whjbsoft.www.po;



/**
 * Khddhpb generated by MyEclipse - Hibernate Tools
 */

public class Khddhpb  implements java.io.Serializable {


    // Fields    

     private Integer ddhpzj;
     private Khdd khdd;
     private String hpbm;
     private String hpmc;
     private String txm;
     private String hpdw;
     private String hplx;
     private String hpxh;
     private String hpgg;
     private Double hpsl;
     private Double hptj;
     private Double hpdj;
     private String tjdw;


    // Constructors

    /** default constructor */
    public Khddhpb() {
    }

    
    /** full constructor */
    public Khddhpb(Khdd khdd, String hpbm, String hpmc, String hpdw, String hplx, String hpxh, String hpgg, Double hpsl, Double hptj, Double hpdj) {
        this.khdd = khdd;
        this.hpbm = hpbm;
        this.hpmc = hpmc;
        this.hpdw = hpdw;
        this.hplx = hplx;
        this.hpxh = hpxh;
        this.hpgg = hpgg;
        this.hpsl = hpsl;
        this.hptj = hptj;
        this.hpdj = hpdj;
    }

   
    // Property accessors

    public Integer getDdhpzj() {
        return this.ddhpzj;
    }
    
    public void setDdhpzj(Integer ddhpzj) {
        this.ddhpzj = ddhpzj;
    }

    public Khdd getKhdd() {
        return this.khdd;
    }
    
    public void setKhdd(Khdd khdd) {
        this.khdd = khdd;
    }

    public String getHpbm() {
        return this.hpbm;
    }
    
    public void setHpbm(String hpbm) {
        this.hpbm = hpbm;
    }

    public String getHpmc() {
        return this.hpmc;
    }
    
    public void setHpmc(String hpmc) {
        this.hpmc = hpmc;
    }

    public String getHpdw() {
        return this.hpdw;
    }
    
    public void setHpdw(String hpdw) {
        this.hpdw = hpdw;
    }

    public String getHplx() {
        return this.hplx;
    }
    
    public void setHplx(String hplx) {
        this.hplx = hplx;
    }

    public String getHpxh() {
        return this.hpxh;
    }
    
    public void setHpxh(String hpxh) {
        this.hpxh = hpxh;
    }

    public String getHpgg() {
        return this.hpgg;
    }
    
    public void setHpgg(String hpgg) {
        this.hpgg = hpgg;
    }

    public Double getHpsl() {
        return this.hpsl;
    }
    
    public void setHpsl(Double hpsl) {
        this.hpsl = hpsl;
    }

    public Double getHptj() {
        return this.hptj;
    }
    
    public void setHptj(Double hptj) {
        this.hptj = hptj;
    }

    public Double getHpdj() {
        return this.hpdj;
    }
    
    public void setHpdj(Double hpdj) {
        this.hpdj = hpdj;
    }


	public String getTjdw() {
		return tjdw;
	}


	public void setTjdw(String tjdw) {
		this.tjdw = tjdw;
	}


	public String getTxm() {
		return txm;
	}


	public void setTxm(String txm) {
		this.txm = txm;
	}
}