package com.whjbsoft.www.po;



/**
 * Khth generated by MyEclipse - Hibernate Tools
 */

public class Khth  implements java.io.Serializable {


    // Fields    

     private Integer thzj;
     private Yspsd yspsd;
     private String thdh;
     private String thyy;
     private String thrqm;
     private String thrq;
     private String fhzd;
     private Integer ssxs;
     private Integer sssysz;


    // Constructors

    /** default constructor */
    public Khth() {
    }

	/** minimal constructor */
    public Khth(Yspsd yspsd) {
        this.yspsd = yspsd;
    }
    
    /** full constructor */
    public Khth(Yspsd yspsd, String thdh, String thyy, String thrqm, String thrq, String fhzd, Integer ssxs, Integer sssysz) {
        this.yspsd = yspsd;
        this.thdh = thdh;
        this.thyy = thyy;
        this.thrqm = thrqm;
        this.thrq = thrq;
        this.fhzd = fhzd;
        this.ssxs = ssxs;
        this.sssysz = sssysz;
    }

   
    // Property accessors

    public Integer getThzj() {
        return this.thzj;
    }
    
    public void setThzj(Integer ddzj) {
        this.thzj = ddzj;
    }

    public String getThdh() {
        return this.thdh;
    }
    
    public void setThdh(String thdh) {
        this.thdh = thdh;
    }

    public String getThyy() {
        return this.thyy;
    }
    
    public void setThyy(String thyy) {
        this.thyy = thyy;
    }

    public String getThrqm() {
        return this.thrqm;
    }
    
    public void setThrqm(String thrqm) {
        this.thrqm = thrqm;
    }

    public String getThrq() {
        return this.thrq;
    }
    
    public void setThrq(String thrq) {
        this.thrq = thrq;
    }

    public String getFhzd() {
        return this.fhzd;
    }
    
    public void setFhzd(String fhzd) {
        this.fhzd = fhzd;
    }

    public Integer getSsxs() {
		return ssxs;
	}

	public void setSsxs(Integer ssxs) {
		this.ssxs = ssxs;
	}

	public Yspsd getYspsd() {
		return yspsd;
	}

	public void setYspsd(Yspsd yspsd) {
		this.yspsd = yspsd;
	}

	public Integer getSssysz() {
        return this.sssysz;
    }
    
    public void setSssysz(Integer sssysz) {
        this.sssysz = sssysz;
    }
   








}