package com.whjbsoft.www.po;

import java.util.HashSet;
import java.util.Set;



/**
 * Pddd generated by MyEclipse - Hibernate Tools
 */

public class Pddd  implements java.io.Serializable {


    // Fields    

     private Integer pdzj;
     private String pdbh;
     private String pdrq;
     private String pdr;
     private String pdlx;
     private Integer sykfzj;
     private String sykfmc;
     private Integer pdzt;
     private Integer ssxs;
     private Integer sssysz;
     private Set kfcppdbs = new HashSet(0);


    // Constructors

    /** default constructor */
    public Pddd() {
    }

    
    /** full constructor */
    public Pddd(String pdbh, String pdrq, String pdr, String pdlx, Integer sykfzj, String sykfmc, Integer pdzt, Integer ssxs, Integer sssysz) {
        this.pdbh = pdbh;
        this.pdrq = pdrq;
        this.pdr = pdr;
        this.pdlx = pdlx;
        this.sykfzj = sykfzj;
        this.sykfmc = sykfmc;
        this.pdzt = pdzt;
        this.ssxs = ssxs;
        this.sssysz = sssysz;
    }

   
    // Property accessors

    public Integer getPdzj() {
        return this.pdzj;
    }
    
    public void setPdzj(Integer pdzj) {
        this.pdzj = pdzj;
    }

    public String getPdbh() {
        return this.pdbh;
    }
    
    public void setPdbh(String pdbh) {
        this.pdbh = pdbh;
    }

    public String getPdrq() {
        return this.pdrq;
    }
    
    public void setPdrq(String pdrq) {
        this.pdrq = pdrq;
    }

    public String getPdr() {
        return this.pdr;
    }
    
    public void setPdr(String pdr) {
        this.pdr = pdr;
    }

    public String getPdlx() {
        return this.pdlx;
    }
    
    public void setPdlx(String pdlx) {
        this.pdlx = pdlx;
    }

    public Integer getSykfzj() {
        return this.sykfzj;
    }
    
    public void setSykfzj(Integer sykfzj) {
        this.sykfzj = sykfzj;
    }

    public String getSykfmc() {
        return this.sykfmc;
    }
    
    public void setSykfmc(String sykfmc) {
        this.sykfmc = sykfmc;
    }

    public Integer getPdzt() {
        return this.pdzt;
    }
    
    public void setPdzt(Integer pdzt) {
        this.pdzt = pdzt;
    }

    public Integer getSsxs() {
        return this.ssxs;
    }
    
    public void setSsxs(Integer ssxs) {
        this.ssxs = ssxs;
    }

    public Integer getSssysz() {
        return this.sssysz;
    }
    
    public void setSssysz(Integer sssysz) {
        this.sssysz = sssysz;
    }


	public Set getKfcppdbs() {
		return kfcppdbs;
	}


	public void setKfcppdbs(Set kfcppdbs) {
		this.kfcppdbs = kfcppdbs;
	}
   








}