package com.whjbsoft.www.po;

import java.util.HashSet;
import java.util.Set;


/**
 * Sbxx generated by MyEclipse - Hibernate Tools
 */

public class Sbxx  implements java.io.Serializable {


    // Fields    

     private Integer sbzj;
     private Kfxx kfxx;
     private String sbbh;
     private String sblx;
     private String sbzt;
     private String rylx;
     private String dllx;
     private String zzl;
     private String kzhc;
     private String kzhk;
     private String kzhg;
     private String dpgd;
     private String ys;
     private String gmrq;
     private String sccj;
     private Double sbjz;
     private String gl;
     private String bzxx;
     private Integer ssxs;
     private Integer sssysz;
     private Set ccsbdds = new HashSet(0);


    // Constructors

    /** default constructor */
    public Sbxx() {
    }

    
    /** full constructor */
    public Sbxx(Kfxx kfxx, String sbbh, String sblx, String sbzt, String rylx, String dllx, String zzl, String kzhc, String kzhk, String kzhg, String dpgd, String ys, String gmrq, String sccj, Double sbjz, String gl, String bzxx, Integer ssxs, Integer sssysz, Set ccsbdds) {
        this.kfxx = kfxx;
        this.sbbh = sbbh;
        this.sblx = sblx;
        this.sbzt = sbzt;
        this.rylx = rylx;
        this.dllx = dllx;
        this.zzl = zzl;
        this.kzhc = kzhc;
        this.kzhk = kzhk;
        this.kzhg = kzhg;
        this.dpgd = dpgd;
        this.ys = ys;
        this.gmrq = gmrq;
        this.sccj = sccj;
        this.sbjz = sbjz;
        this.gl = gl;
        this.bzxx = bzxx;
        this.ssxs = ssxs;
        this.sssysz = sssysz;
        this.ccsbdds = ccsbdds;
    }

   
    // Property accessors

    public Integer getSbzj() {
        return this.sbzj;
    }
    
    public void setSbzj(Integer sbzj) {
        this.sbzj = sbzj;
    }

    public Kfxx getKfxx() {
        return this.kfxx;
    }
    
    public void setKfxx(Kfxx kfxx) {
        this.kfxx = kfxx;
    }

    public String getSbbh() {
        return this.sbbh;
    }
    
    public void setSbbh(String sbbh) {
        this.sbbh = sbbh;
    }

    public String getSblx() {
        return this.sblx;
    }
    
    public void setSblx(String sblx) {
        this.sblx = sblx;
    }

    public String getSbzt() {
        return this.sbzt;
    }
    
    public void setSbzt(String sbzt) {
        this.sbzt = sbzt;
    }

    public String getRylx() {
        return this.rylx;
    }
    
    public void setRylx(String rylx) {
        this.rylx = rylx;
    }

    public String getDllx() {
        return this.dllx;
    }
    
    public void setDllx(String dllx) {
        this.dllx = dllx;
    }

    public String getZzl() {
        return this.zzl;
    }
    
    public void setZzl(String zzl) {
        this.zzl = zzl;
    }

    public String getKzhc() {
        return this.kzhc;
    }
    
    public void setKzhc(String kzhc) {
        this.kzhc = kzhc;
    }

    public String getKzhk() {
        return this.kzhk;
    }
    
    public void setKzhk(String kzhk) {
        this.kzhk = kzhk;
    }

    public String getKzhg() {
        return this.kzhg;
    }
    
    public void setKzhg(String kzhg) {
        this.kzhg = kzhg;
    }

    public String getDpgd() {
        return this.dpgd;
    }
    
    public void setDpgd(String dpgd) {
        this.dpgd = dpgd;
    }

    public String getYs() {
        return this.ys;
    }
    
    public void setYs(String ys) {
        this.ys = ys;
    }

    public String getGmrq() {
        return this.gmrq;
    }
    
    public void setGmrq(String gmrq) {
        this.gmrq = gmrq;
    }

    public String getSccj() {
        return this.sccj;
    }
    
    public void setSccj(String sccj) {
        this.sccj = sccj;
    }

    public Double getSbjz() {
        return this.sbjz;
    }
    
    public void setSbjz(Double sbjz) {
        this.sbjz = sbjz;
    }

    public String getGl() {
        return this.gl;
    }
    
    public void setGl(String gl) {
        this.gl = gl;
    }

    public String getBzxx() {
        return this.bzxx;
    }
    
    public void setBzxx(String bzxx) {
        this.bzxx = bzxx;
    }

    public Integer getSsxs() {
        return this.ssxs;
    }
    
    public void setSsxs(Integer ssxs) {
        this.ssxs = ssxs;
    }

    public Integer getSssysz() {
        return this.sssysz;
    }
    
    public void setSssysz(Integer sssysz) {
        this.sssysz = sssysz;
    }

    public Set getCcsbdds() {
        return this.ccsbdds;
    }
    
    public void setCcsbdds(Set ccsbdds) {
        this.ccsbdds = ccsbdds;
    }
   








}