package com.whjbsoft.www.po;



/**
 * Sjhp generated by MyEclipse - Hibernate Tools
 */

public class Sjhp  implements java.io.Serializable {


    // Fields    

     private Integer sjhpzj;
     private Sjxx sjxx;
     private String hpbm;
     private Double hpsl;


    // Constructors

    /** default constructor */
    public Sjhp() {
    }

    
    /** full constructor */
    public Sjhp(Sjxx sjxx, String hpbm, Double hpsl) {
        this.sjxx = sjxx;
        this.hpbm = hpbm;
        this.hpsl = hpsl;
    }

   
    // Property accessors

    public Integer getSjhpzj() {
        return this.sjhpzj;
    }
    
    public void setSjhpzj(Integer sjhpzj) {
        this.sjhpzj = sjhpzj;
    }

    public Sjxx getSjxx() {
        return this.sjxx;
    }
    
    public void setSjxx(Sjxx sjxx) {
        this.sjxx = sjxx;
    }

    public String getHpbm() {
        return this.hpbm;
    }
    
    public void setHpbm(String hpbm) {
        this.hpbm = hpbm;
    }

    public Double getHpsl() {
        return this.hpsl;
    }
    
    public void setHpsl(Double hpsl) {
        this.hpsl = hpsl;
    }
   








}