package com.whjbsoft.www.po;

import java.util.HashSet;
import java.util.Set;


/**
 * Sjxx generated by MyEclipse - Hibernate Tools
 */

public class Sjxx  implements java.io.Serializable {


    // Fields    

     private Integer sjzj;
     private String sjbh;
     private String sjmc;
     private Integer cjrzj;
     private String cjsj;
     private Integer sjzt;
     private Set sjhps = new HashSet(0);
     private Set ktxxes = new HashSet(0);
     private Set djxxes = new HashSet(0);
     private Set sysjs = new HashSet(0);


    // Constructors

    /** default constructor */
    public Sjxx() {
    }

    
    /** full constructor */
    public Sjxx(String sjbh, String sjmc, Integer cjrzj, String cjsj, Integer sjzt, Set sjhps, Set ktxxes, Set djxxes, Set sysjs) {
        this.sjbh = sjbh;
        this.sjmc = sjmc;
        this.cjrzj = cjrzj;
        this.cjsj = cjsj;
        this.sjzt = sjzt;
        this.sjhps = sjhps;
        this.ktxxes = ktxxes;
        this.djxxes = djxxes;
        this.sysjs = sysjs;
    }

   
    // Property accessors

    public Integer getSjzj() {
        return this.sjzj;
    }
    
    public void setSjzj(Integer sjzj) {
        this.sjzj = sjzj;
    }

    public String getSjbh() {
        return this.sjbh;
    }
    
    public void setSjbh(String sjbh) {
        this.sjbh = sjbh;
    }

    public String getSjmc() {
        return this.sjmc;
    }
    
    public void setSjmc(String sjmc) {
        this.sjmc = sjmc;
    }

    public Integer getCjrzj() {
        return this.cjrzj;
    }
    
    public void setCjrzj(Integer cjrzj) {
        this.cjrzj = cjrzj;
    }

    public String getCjsj() {
        return this.cjsj;
    }
    
    public void setCjsj(String cjsj) {
        this.cjsj = cjsj;
    }

    public Integer getSjzt() {
        return this.sjzt;
    }
    
    public void setSjzt(Integer sjzt) {
        this.sjzt = sjzt;
    }

    public Set getSjhps() {
        return this.sjhps;
    }
    
    public void setSjhps(Set sjhps) {
        this.sjhps = sjhps;
    }

    public Set getKtxxes() {
        return this.ktxxes;
    }
    
    public void setKtxxes(Set ktxxes) {
        this.ktxxes = ktxxes;
    }

    public Set getDjxxes() {
        return this.djxxes;
    }
    
    public void setDjxxes(Set djxxes) {
        this.djxxes = djxxes;
    }

    public Set getSysjs() {
        return this.sysjs;
    }
    
    public void setSysjs(Set sysjs) {
        this.sysjs = sysjs;
    }
   








}