package com.whjbsoft.www.po;



/**
 * Sjzdmx generated by MyEclipse - Hibernate Tools
 */

public class Sjzdmx  implements java.io.Serializable {


    // Fields    

     private Integer sjzdmxzj;
     private Sjzd sjzd;
     private Integer fqzj;
     private String sjzdmxbh;
     private String sjzdmxmc;
     private String field1;
     private String field2;
     private String field3;
     private String field4;
     private String field5;
     private String field6;
     private String field7;
     private String field8;
     private Integer kfcz;


    // Constructors

    /** default constructor */
    public Sjzdmx() {
    }

    
    /** full constructor */
    public Sjzdmx(Sjzd sjzd, Integer fqzj, String sjzdmxbh, String sjzdmxmc, String field1, String field2, String field3, String field4, String field5, String field6, String field7, String field8, Integer kfcz) {
        this.sjzd = sjzd;
        this.fqzj = fqzj;
        this.sjzdmxbh = sjzdmxbh;
        this.sjzdmxmc = sjzdmxmc;
        this.field1 = field1;
        this.field2 = field2;
        this.field3 = field3;
        this.field4 = field4;
        this.field5 = field5;
        this.field6 = field6;
        this.field7 = field7;
        this.field8 = field8;
        this.kfcz = kfcz;
    }

   
    // Property accessors

    public Integer getSjzdmxzj() {
        return this.sjzdmxzj;
    }
    
    public void setSjzdmxzj(Integer sjzdmxzj) {
        this.sjzdmxzj = sjzdmxzj;
    }

    public Sjzd getSjzd() {
        return this.sjzd;
    }
    
    public void setSjzd(Sjzd sjzd) {
        this.sjzd = sjzd;
    }

    public Integer getFqzj() {
        return this.fqzj;
    }
    
    public void setFqzj(Integer fqzj) {
        this.fqzj = fqzj;
    }

    public String getSjzdmxbh() {
        return this.sjzdmxbh;
    }
    
    public void setSjzdmxbh(String sjzdmxbh) {
        this.sjzdmxbh = sjzdmxbh;
    }

    public String getSjzdmxmc() {
        return this.sjzdmxmc;
    }
    
    public void setSjzdmxmc(String sjzdmxmc) {
        this.sjzdmxmc = sjzdmxmc;
    }

    public String getField1() {
        return this.field1;
    }
    
    public void setField1(String field1) {
        this.field1 = field1;
    }

    public String getField2() {
        return this.field2;
    }
    
    public void setField2(String field2) {
        this.field2 = field2;
    }

    public String getField3() {
        return this.field3;
    }
    
    public void setField3(String field3) {
        this.field3 = field3;
    }

    public String getField4() {
        return this.field4;
    }
    
    public void setField4(String field4) {
        this.field4 = field4;
    }

    public String getField5() {
        return this.field5;
    }
    
    public void setField5(String field5) {
        this.field5 = field5;
    }

    public String getField6() {
        return this.field6;
    }
    
    public void setField6(String field6) {
        this.field6 = field6;
    }

    public String getField7() {
        return this.field7;
    }
    
    public void setField7(String field7) {
        this.field7 = field7;
    }

    public String getField8() {
        return this.field8;
    }
    
    public void setField8(String field8) {
        this.field8 = field8;
    }

    public Integer getKfcz() {
        return this.kfcz;
    }
    
    public void setKfcz(Integer kfcz) {
        this.kfcz = kfcz;
    }
   








}