package com.whjbsoft.www.po;

import java.util.HashSet;
import java.util.Set;


/**
 * Stgl generated by MyEclipse - Hibernate Tools
 */

public class Stgl  implements java.io.Serializable {


    // Fields    

     private Integer stzj;
     private String stmc;
     private String stlx;
     private Integer sfyk;
     private Integer czlx;
     private Set ktxxs = new HashSet(0);


    // Constructors

    /** default constructor */
    public Stgl() {
    }

    
    /** full constructor */
    public Stgl(String stmc, String stlx, Integer sfyk, Integer czlx, Set ktxxs) {
        this.stmc = stmc;
        this.stlx = stlx;
        this.sfyk = sfyk;
        this.czlx = czlx;
        this.ktxxs = ktxxs;
    }

   
    // Property accessors

    public Integer getStzj() {
        return this.stzj;
    }
    
    public void setStzj(Integer stzj) {
        this.stzj = stzj;
    }

    public String getStmc() {
        return this.stmc;
    }
    
    public void setStmc(String stmc) {
        this.stmc = stmc;
    }

    public String getStlx() {
        return this.stlx;
    }
    
    public void setStlx(String stlx) {
        this.stlx = stlx;
    }

    public Integer getSfyk() {
        return this.sfyk;
    }
    
    public void setSfyk(Integer sfyk) {
        this.sfyk = sfyk;
    }

    public Integer getCzlx() {
        return this.czlx;
    }
    
    public void setCzlx(Integer czlx) {
        this.czlx = czlx;
    }

    public Set getKtxxs() {
        return this.ktxxs;
    }
    
    public void setKtxxs(Set ktxxs) {
        this.ktxxs = ktxxs;
    }
   








}