package com.whjbsoft.www.po;



/**
 * SysjId generated by MyEclipse - Hibernate Tools
 */

public class SysjId  implements java.io.Serializable {


    // Fields    

     private Integer syszzj;
     private Integer sjzj;


    // Constructors

    /** default constructor */
    public SysjId() {
    }

    
    /** full constructor */
    public SysjId(Integer syszzj, Integer sjzj) {
        this.syszzj = syszzj;
        this.sjzj = sjzj;
    }

   
    // Property accessors

    public Integer getSyszzj() {
        return this.syszzj;
    }
    
    public void setSyszzj(Integer syszzj) {
        this.syszzj = syszzj;
    }

    public Integer getSjzj() {
        return this.sjzj;
    }
    
    public void setSjzj(Integer sjzj) {
        this.sjzj = sjzj;
    }
   



   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof SysjId) ) return false;
		 SysjId castOther = ( SysjId ) other; 
         
		 return ( (this.getSyszzj()==castOther.getSyszzj()) || ( this.getSyszzj()!=null && castOther.getSyszzj()!=null && this.getSyszzj().equals(castOther.getSyszzj()) ) )
 && ( (this.getSjzj()==castOther.getSjzj()) || ( this.getSjzj()!=null && castOther.getSjzj()!=null && this.getSjzj().equals(castOther.getSjzj()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getSyszzj() == null ? 0 : this.getSyszzj().hashCode() );
         result = 37 * result + ( getSjzj() == null ? 0 : this.getSjzj().hashCode() );
         return result;
   }   





}