package com.whjbsoft.www.po;

import java.util.HashSet;
import java.util.Set;


/**
 * Sysz generated by MyEclipse - Hibernate Tools
 */

public class Sysz  implements java.io.Serializable {


    // Fields    

     private Integer syszzj;
     private String syszmc;
     private Integer syjxsj;
     private Integer syszzt;
     private Integer czrzj;
     private Set sysjs = new HashSet(0);


    // Constructors

    /** default constructor */
    public Sysz() {
    }

    
    /** full constructor */
    public Sysz(String syszmc, Integer syjxsj, Integer syszzt, Integer czrzj, Set sysjs) {
        this.syszmc = syszmc;
        this.syjxsj = syjxsj;
        this.syszzt = syszzt;
        this.czrzj = czrzj;
        this.sysjs = sysjs;
    }

   
    // Property accessors

    public Integer getSyszzj() {
        return this.syszzj;
    }
    
    public void setSyszzj(Integer syszzj) {
        this.syszzj = syszzj;
    }

    public String getSyszmc() {
        return this.syszmc;
    }
    
    public void setSyszmc(String syszmc) {
        this.syszmc = syszmc;
    }

    public Integer getSyjxsj() {
        return this.syjxsj;
    }
    
    public void setSyjxsj(Integer syjxsj) {
        this.syjxsj = syjxsj;
    }

    public Integer getSyszzt() {
        return this.syszzt;
    }
    
    public void setSyszzt(Integer syszzt) {
        this.syszzt = syszzt;
    }

    public Integer getCzrzj() {
        return this.czrzj;
    }
    
    public void setCzrzj(Integer czrzj) {
        this.czrzj = czrzj;
    }

    public Set getSysjs() {
        return this.sysjs;
    }
    
    public void setSysjs(Set sysjs) {
        this.sysjs = sysjs;
    }
   








}