package com.whjbsoft.www.po;



/**
 * Xlyh generated by MyEclipse - Hibernate Tools
 */

public class Xlyh  implements java.io.Serializable {


    // Fields    

     private XlyhId id;
     private Bxxx bxxx;
     private Ysddxx ysddxx;


    // Constructors

    /** default constructor */
    public Xlyh() {
    }

    
    /** full constructor */
    public Xlyh(Bxxx bxxx, Ysddxx ysddxx) {
        this.bxxx = bxxx;
        this.ysddxx = ysddxx;
    }

   
    // Property accessors

    public XlyhId getId() {
        return this.id;
    }
    
    public void setId(XlyhId id) {
        this.id = id;
    }

    public Bxxx getBxxx() {
        return this.bxxx;
    }
    
    public void setBxxx(Bxxx bxxx) {
        this.bxxx = bxxx;
    }

    public Ysddxx getYsddxx() {
        return this.ysddxx;
    }
    
    public void setYsddxx(Ysddxx ysddxx) {
        this.ysddxx = ysddxx;
    }
   








}