package com.whjbsoft.www.po;



/**
 * Xsgwxx generated by MyEclipse - Hibernate Tools
 */

public class Xsgwxx  implements java.io.Serializable {


    // Fields    

     private XsgwxxId id;


    // Constructors

    /** default constructor */
    public Xsgwxx() {
    }

    

   
    // Property accessors

    public Xsgwxx(XsgwxxId id) {
		this.id = id;
	}




	public XsgwxxId getId() {
        return this.id;
    }
    
    public void setId(XsgwxxId id) {
        this.id = id;
    }
   








}