package com.whjbsoft.www.po;



/**
 * Ykmx generated by MyEclipse - Hibernate Tools
 */

public class Ykmx  implements java.io.Serializable {


    // Fields    

     private Integer ykmxzj;
     private Cwxx cwxxByCwxCwzj;
     private Cwxx cwxxByCwzj;
     private Ykdd ykdd;
     private Double ykhpsl;
     private Double ykshsl;


    // Constructors

    /** default constructor */
    public Ykmx() {
    }

    
    /** full constructor */
    public Ykmx(Cwxx cwxxByCwxCwzj, Cwxx cwxxByCwzj, Ykdd ykdd) {
        this.cwxxByCwxCwzj = cwxxByCwxCwzj;
        this.cwxxByCwzj = cwxxByCwzj;
        this.ykdd = ykdd;
    }

   
    // Property accessors

    public Integer getYkmxzj() {
        return this.ykmxzj;
    }
    
    public void setYkmxzj(Integer ykmxzj) {
        this.ykmxzj = ykmxzj;
    }

    public Cwxx getCwxxByCwxCwzj() {
        return this.cwxxByCwxCwzj;
    }
    
    public void setCwxxByCwxCwzj(Cwxx cwxxByCwxCwzj) {
        this.cwxxByCwxCwzj = cwxxByCwxCwzj;
    }

    public Cwxx getCwxxByCwzj() {
        return this.cwxxByCwzj;
    }
    
    public void setCwxxByCwzj(Cwxx cwxxByCwzj) {
        this.cwxxByCwzj = cwxxByCwzj;
    }

    public Ykdd getYkdd() {
        return this.ykdd;
    }
    
    public void setYkdd(Ykdd ykdd) {
        this.ykdd = ykdd;
    }


	public Double getYkhpsl() {
		return ykhpsl;
	}


	public void setYkhpsl(Double ykhpsl) {
		this.ykhpsl = ykhpsl;
	}


	public Double getYkshsl() {
		return ykshsl;
	}


	public void setYkshsl(Double ykshsl) {
		this.ykshsl = ykshsl;
	}
   








}