package com.whjbsoft.www.po;

import java.util.HashSet;
import java.util.Set;


/**
 * Ylxx generated by MyEclipse - Hibernate Tools
 */

public class Ylxx  implements java.io.Serializable {


    // Fields    

     private Integer ylzj;
     private String ylbh;
     private String cllx;
     private String cph;
     private String kzhc;
     private String kzhk;
     private String kzhg;
     private String zdcr;
     private String zddxcc;
     private String zdhz;
     private String clpp;
     private String ssjg;
     private String syzt;
     private String bzxx;
     private Integer ssxs;
     private Integer sssysz;
     private Set yscldds = new HashSet(0);


    // Constructors

    /** default constructor */
    public Ylxx() {
    }

    
    /** full constructor */
    public Ylxx(String ylbh, String cllx, String cph, String kzhc, String kzhk, String kzhg, String zdcr, String zddxcc, String zdhz, String clpp, String ssjg, String syzt, String bzxx, Integer ssxs, Integer sssysz, Set yscldds) {
        this.ylbh = ylbh;
        this.cllx = cllx;
        this.cph = cph;
        this.kzhc = kzhc;
        this.kzhk = kzhk;
        this.kzhg = kzhg;
        this.zdcr = zdcr;
        this.zddxcc = zddxcc;
        this.zdhz = zdhz;
        this.clpp = clpp;
        this.ssjg = ssjg;
        this.syzt = syzt;
        this.bzxx = bzxx;
        this.ssxs = ssxs;
        this.sssysz = sssysz;
        this.yscldds = yscldds;
    }

   
    // Property accessors

    public Integer getYlzj() {
        return this.ylzj;
    }
    
    public void setYlzj(Integer ylzj) {
        this.ylzj = ylzj;
    }

    public String getYlbh() {
        return this.ylbh;
    }
    
    public void setYlbh(String ylbh) {
        this.ylbh = ylbh;
    }

    public String getCllx() {
        return this.cllx;
    }
    
    public void setCllx(String cllx) {
        this.cllx = cllx;
    }

    public String getCph() {
        return this.cph;
    }
    
    public void setCph(String cph) {
        this.cph = cph;
    }

    public String getKzhc() {
        return this.kzhc;
    }
    
    public void setKzhc(String kzhc) {
        this.kzhc = kzhc;
    }

    public String getKzhk() {
        return this.kzhk;
    }
    
    public void setKzhk(String kzhk) {
        this.kzhk = kzhk;
    }

    public String getKzhg() {
        return this.kzhg;
    }
    
    public void setKzhg(String kzhg) {
        this.kzhg = kzhg;
    }

    public String getZdcr() {
        return this.zdcr;
    }
    
    public void setZdcr(String zdcr) {
        this.zdcr = zdcr;
    }

    public String getZddxcc() {
        return this.zddxcc;
    }
    
    public void setZddxcc(String zddxcc) {
        this.zddxcc = zddxcc;
    }

    public String getZdhz() {
        return this.zdhz;
    }
    
    public void setZdhz(String zdhz) {
        this.zdhz = zdhz;
    }

    public String getClpp() {
        return this.clpp;
    }
    
    public void setClpp(String clpp) {
        this.clpp = clpp;
    }

    public String getSsjg() {
        return this.ssjg;
    }
    
    public void setSsjg(String ssjg) {
        this.ssjg = ssjg;
    }

    public String getSyzt() {
        return this.syzt;
    }
    
    public void setSyzt(String syzt) {
        this.syzt = syzt;
    }

    public String getBzxx() {
        return this.bzxx;
    }
    
    public void setBzxx(String bzxx) {
        this.bzxx = bzxx;
    }

    public Integer getSsxs() {
        return this.ssxs;
    }
    
    public void setSsxs(Integer ssxs) {
        this.ssxs = ssxs;
    }

    public Integer getSssysz() {
        return this.sssysz;
    }
    
    public void setSssysz(Integer sssysz) {
        this.sssysz = sssysz;
    }

    public Set getYscldds() {
        return this.yscldds;
    }
    
    public void setYscldds(Set yscldds) {
        this.yscldds = yscldds;
    }
   








}