package com.whjbsoft.www.po;



/**
 * Yscldd generated by MyEclipse - Hibernate Tools
 */

public class Yscldd  implements java.io.Serializable {


    // Fields    

     private YsclddId id;
     private Ylxx ylxx;
     private Ysddxx ysddxx;


    // Constructors

    /** default constructor */
    public Yscldd() {
    }

    
    /** full constructor */
    public Yscldd(Ylxx ylxx, Ysddxx ysddxx) {
        this.ylxx = ylxx;
        this.ysddxx = ysddxx;
    }

   
    // Property accessors

    public YsclddId getId() {
        return this.id;
    }
    
    public void setId(YsclddId id) {
        this.id = id;
    }

    public Ylxx getYlxx() {
        return this.ylxx;
    }
    
    public void setYlxx(Ylxx ylxx) {
        this.ylxx = ylxx;
    }

    public Ysddxx getYsddxx() {
        return this.ysddxx;
    }
    
    public void setYsddxx(Ysddxx ysddxx) {
        this.ysddxx = ysddxx;
    }
   








}