package com.whjbsoft.www.po;



/**
 * YsclddId generated by MyEclipse - Hibernate Tools
 */

public class YsclddId  implements java.io.Serializable {


    // Fields    

     private Integer ylzj;
     private Integer ysddzj;


    // Constructors

    /** default constructor */
    public YsclddId() {
    }

    
    /** full constructor */
    public YsclddId(Integer ylzj, Integer ysddzj) {
        this.ylzj = ylzj;
        this.ysddzj = ysddzj;
    }

   
    // Property accessors

    public Integer getYlzj() {
        return this.ylzj;
    }
    
    public void setYlzj(Integer ylzj) {
        this.ylzj = ylzj;
    }

    public Integer getYsddzj() {
        return this.ysddzj;
    }
    
    public void setYsddzj(Integer ysddzj) {
        this.ysddzj = ysddzj;
    }
   



   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof YsclddId) ) return false;
		 YsclddId castOther = ( YsclddId ) other; 
         
		 return ( (this.getYlzj()==castOther.getYlzj()) || ( this.getYlzj()!=null && castOther.getYlzj()!=null && this.getYlzj().equals(castOther.getYlzj()) ) )
 && ( (this.getYsddzj()==castOther.getYsddzj()) || ( this.getYsddzj()!=null && castOther.getYsddzj()!=null && this.getYsddzj().equals(castOther.getYsddzj()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getYlzj() == null ? 0 : this.getYlzj().hashCode() );
         result = 37 * result + ( getYsddzj() == null ? 0 : this.getYsddzj().hashCode() );
         return result;
   }   





}