package com.whjbsoft.www.po;



/**
 * YsdddId generated by MyEclipse - Hibernate Tools
 */

public class YsdddId  implements java.io.Serializable {


    // Fields    

     private Integer ysdzj;
     private Integer ysddzj;


    // Constructors

    /** default constructor */
    public YsdddId() {
    }

    
    /** full constructor */
    public YsdddId(Integer ysdzj, Integer ysddzj) {
        this.ysdzj = ysdzj;
        this.ysddzj = ysddzj;
    }

   
    // Property accessors

    public Integer getYsdzj() {
        return this.ysdzj;
    }
    
    public void setYsdzj(Integer ysdzj) {
        this.ysdzj = ysdzj;
    }

    public Integer getYsddzj() {
        return this.ysddzj;
    }
    
    public void setYsddzj(Integer ysddzj) {
        this.ysddzj = ysddzj;
    }
   



   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof YsdddId) ) return false;
		 YsdddId castOther = ( YsdddId ) other; 
         
		 return ( (this.getYsdzj()==castOther.getYsdzj()) || ( this.getYsdzj()!=null && castOther.getYsdzj()!=null && this.getYsdzj().equals(castOther.getYsdzj()) ) )
 && ( (this.getYsddzj()==castOther.getYsddzj()) || ( this.getYsddzj()!=null && castOther.getYsddzj()!=null && this.getYsddzj().equals(castOther.getYsddzj()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getYsdzj() == null ? 0 : this.getYsdzj().hashCode() );
         result = 37 * result + ( getYsddzj() == null ? 0 : this.getYsddzj().hashCode() );
         return result;
   }   





}