package com.whjbsoft.www.po;

import java.util.HashSet;
import java.util.Set;


/**
 * Yspsd generated by MyEclipse - Hibernate Tools
 */

public class Yspsd  implements java.io.Serializable {


    // Fields    

     private Integer ysdzj;
     private Khht khht;
     private String ysdbh;
     private String ysdlx;
     private String dhsj;
     private String qhsj;
     private String ysfs;
     private Double yf;
     private Double zf;
     private Double fyxj;
     private Integer tbsm;
     private Double tbje;
     private Double bxf;
     private Double yzfhj;
     private Double ysk;
     private String yssm;
     private String zdr;
     private String zdsj;
     private Integer yszt;
     private String shrqz;
     private String shrqzsj;
     private Integer sffd;
     private Integer sfth;
     private Integer ssxs;
     private Integer sssysz;
     private Set ysddds = new HashSet(0);
     private Set<Khfk> khfks = new HashSet<Khfk>(0);
     private Set<Khth> khths = new HashSet<Khth>(0);


    // Constructors

    /** default constructor */
    public Yspsd() {
    }

    
    /** full constructor */
    public Yspsd(Khht khht, String ysdbh, String ysdlx, String dhsj, String qhsj, String ysfs, Double yf, Double zf, Double fyxj, Integer tbsm, Double tbje, Double bxf, Double yzfhj, Double ysk, String yssm, String zdr, String zdsj, Integer yszt, String shrqz, String shrqzsj, Integer ssxs, Integer sssysz, Set ysddds) {
        this.khht = khht;
        this.ysdbh = ysdbh;
        this.ysdlx = ysdlx;
        this.dhsj = dhsj;
        this.qhsj = qhsj;
        this.ysfs = ysfs;
        this.yf = yf;
        this.zf = zf;
        this.fyxj = fyxj;
        this.tbsm = tbsm;
        this.tbje = tbje;
        this.bxf = bxf;
        this.yzfhj = yzfhj;
        this.ysk = ysk;
        this.yssm = yssm;
        this.zdr = zdr;
        this.zdsj = zdsj;
        this.yszt = yszt;
        this.shrqz = shrqz;
        this.shrqzsj = shrqzsj;
        this.ssxs = ssxs;
        this.sssysz = sssysz;
        this.ysddds = ysddds;
    }

   
    // Property accessors

    public Integer getYsdzj() {
        return this.ysdzj;
    }
    
    public void setYsdzj(Integer ysdzj) {
        this.ysdzj = ysdzj;
    }

    public Khht getKhht() {
        return this.khht;
    }
    
    public void setKhht(Khht khht) {
        this.khht = khht;
    }

    public String getYsdbh() {
        return this.ysdbh;
    }
    
    public void setYsdbh(String ysdbh) {
        this.ysdbh = ysdbh;
    }

    public String getYsdlx() {
        return this.ysdlx;
    }
    
    public void setYsdlx(String ysdlx) {
        this.ysdlx = ysdlx;
    }

    public String getDhsj() {
        return this.dhsj;
    }
    
    public void setDhsj(String dhsj) {
        this.dhsj = dhsj;
    }

    public String getQhsj() {
        return this.qhsj;
    }
    
    public void setQhsj(String qhsj) {
        this.qhsj = qhsj;
    }

    public String getYsfs() {
        return this.ysfs;
    }
    
    public void setYsfs(String ysfs) {
        this.ysfs = ysfs;
    }

    public Double getYf() {
        return this.yf;
    }
    
    public void setYf(Double yf) {
        this.yf = yf;
    }

    public Double getZf() {
        return this.zf;
    }
    
    public void setZf(Double zf) {
        this.zf = zf;
    }

    public Double getFyxj() {
        return this.fyxj;
    }
    
    public void setFyxj(Double fyxj) {
        this.fyxj = fyxj;
    }

    public Integer getTbsm() {
        return this.tbsm;
    }
    
    public void setTbsm(Integer tbsm) {
        this.tbsm = tbsm;
    }

    public Double getTbje() {
        return this.tbje;
    }
    
    public void setTbje(Double tbje) {
        this.tbje = tbje;
    }

    public Double getBxf() {
        return this.bxf;
    }
    
    public void setBxf(Double bxf) {
        this.bxf = bxf;
    }

    public Double getYzfhj() {
        return this.yzfhj;
    }
    
    public void setYzfhj(Double yzfhj) {
        this.yzfhj = yzfhj;
    }

    public Double getYsk() {
        return this.ysk;
    }
    
    public void setYsk(Double ysk) {
        this.ysk = ysk;
    }

    public String getYssm() {
        return this.yssm;
    }
    
    public void setYssm(String yssm) {
        this.yssm = yssm;
    }

    public String getZdr() {
        return this.zdr;
    }
    
    public void setZdr(String zdr) {
        this.zdr = zdr;
    }

    public String getZdsj() {
        return this.zdsj;
    }
    
    public void setZdsj(String zdsj) {
        this.zdsj = zdsj;
    }

    public Integer getYszt() {
        return this.yszt;
    }
    
    public void setYszt(Integer yszt) {
        this.yszt = yszt;
    }

    public String getShrqz() {
        return this.shrqz;
    }
    
    public void setShrqz(String shrqz) {
        this.shrqz = shrqz;
    }

    public String getShrqzsj() {
        return this.shrqzsj;
    }
    
    public void setShrqzsj(String shrqzsj) {
        this.shrqzsj = shrqzsj;
    }

    public Integer getSsxs() {
        return this.ssxs;
    }
    
    public void setSsxs(Integer ssxs) {
        this.ssxs = ssxs;
    }

    public Integer getSssysz() {
        return this.sssysz;
    }
    
    public void setSssysz(Integer sssysz) {
        this.sssysz = sssysz;
    }

    public Set getYsddds() {
        return this.ysddds;
    }
    
    public void setYsddds(Set ysddds) {
        this.ysddds = ysddds;
    }


	public Set<Khfk> getKhfks() {
		return khfks;
	}


	public void setKhfks(Set<Khfk> khfks) {
		this.khfks = khfks;
	}


	public Set<Khth> getKhths() {
		return khths;
	}


	public void setKhths(Set<Khth> khths) {
		this.khths = khths;
	}


	public Integer getSffd() {
		return sffd;
	}


	public void setSffd(Integer sffd) {
		this.sffd = sffd;
	}


	public Integer getSfth() {
		return sfth;
	}


	public void setSfth(Integer sfth) {
		this.sfth = sfth;
	}
}