package com.whjbsoft.www.po;



/**
 * Ysrydd generated by MyEclipse - Hibernate Tools
 */

public class Ysrydd  implements java.io.Serializable {


    // Fields    

     private YsryddId id;
     private Ysddxx ysddxx;
     private Ygxx ygxx;


    // Constructors

    /** default constructor */
    public Ysrydd() {
    }

    
    /** full constructor */
    public Ysrydd(Ysddxx ysddxx, Ygxx ygxx) {
        this.ysddxx = ysddxx;
        this.ygxx = ygxx;
    }

   
    // Property accessors

    public YsryddId getId() {
        return this.id;
    }
    
    public void setId(YsryddId id) {
        this.id = id;
    }

    public Ysddxx getYsddxx() {
        return this.ysddxx;
    }
    
    public void setYsddxx(Ysddxx ysddxx) {
        this.ysddxx = ysddxx;
    }

    public Ygxx getYgxx() {
        return this.ygxx;
    }
    
    public void setYgxx(Ygxx ygxx) {
        this.ygxx = ygxx;
    }
   








}