package com.whjbsoft.www.po;



/**
 * Zdgl generated by MyEclipse - Hibernate Tools
 */

public class Zdgl  implements java.io.Serializable {


    // Fields    

     private Integer zzdzj;
     private String zzdbh;
     private String syhth;
     private String bz;
     private String jsfs;
     private String khqm;
     private String zdrq;
     private Integer sfhx;
     private String fkzh;
     private Double yfk;
     private Double yf;
     private Double zf;
     private Double bf;
     private Double ccfy;
     private Double ccyqfy;
     private Double zje;
     private String ssjg;
     private Integer ssxs;
     private Integer sssysz;
     private Integer ssxt;


    // Constructors

    public Integer getSsxt() {
		return ssxt;
	}


	public void setSsxt(Integer ssxt) {
		this.ssxt = ssxt;
	}


	/** default constructor */
    public Zdgl() {
    }

    
    /** full constructor */
    public Zdgl(String zzdbh, String syhth, String bz, String jsfs, String khqm, String zdrq, Integer sfhx, String fkzh, Double yf, Double zf, Double bf, Double ccfy, Double ccyqfy, Double zje, Integer ssxs, Integer sssysz) {
        this.zzdbh = zzdbh;
        this.syhth = syhth;
        this.bz = bz;
        this.jsfs = jsfs;
        this.khqm = khqm;
        this.zdrq = zdrq;
        this.sfhx = sfhx;
        this.fkzh = fkzh;
        this.yf = yf;
        this.zf = zf;
        this.bf = bf;
        this.ccfy = ccfy;
        this.ccyqfy = ccyqfy;
        this.zje = zje;
        this.ssxs = ssxs;
        this.sssysz = sssysz;
    }

   
    // Property accessors

    public Integer getZzdzj() {
        return this.zzdzj;
    }
    
    public void setZzdzj(Integer zzdzj) {
        this.zzdzj = zzdzj;
    }

    public String getZzdbh() {
        return this.zzdbh;
    }
    
    public void setZzdbh(String zzdbh) {
        this.zzdbh = zzdbh;
    }

    public String getSyhth() {
        return this.syhth;
    }
    
    public void setSyhth(String syhth) {
        this.syhth = syhth;
    }

    public String getBz() {
        return this.bz;
    }
    
    public void setBz(String bz) {
        this.bz = bz;
    }

    public String getJsfs() {
        return this.jsfs;
    }
    
    public void setJsfs(String jsfs) {
        this.jsfs = jsfs;
    }

    public String getKhqm() {
        return this.khqm;
    }
    
    public void setKhqm(String khqm) {
        this.khqm = khqm;
    }

    public String getZdrq() {
        return this.zdrq;
    }
    
    public void setZdrq(String zdrq) {
        this.zdrq = zdrq;
    }

    public Integer getSfhx() {
        return this.sfhx;
    }
    
    public void setSfhx(Integer sfhx) {
        this.sfhx = sfhx;
    }

    public String getFkzh() {
        return this.fkzh;
    }
    
    public void setFkzh(String fkzh) {
        this.fkzh = fkzh;
    }

    public Double getYf() {
        return this.yf;
    }
    
    public void setYf(Double yf) {
        this.yf = yf;
    }

    public Double getZf() {
        return this.zf;
    }
    
    public void setZf(Double zf) {
        this.zf = zf;
    }

    public Double getBf() {
        return this.bf;
    }
    
    public void setBf(Double bf) {
        this.bf = bf;
    }

    public Double getCcfy() {
        return this.ccfy;
    }
    
    public void setCcfy(Double ccfy) {
        this.ccfy = ccfy;
    }

    public Double getCcyqfy() {
        return this.ccyqfy;
    }
    
    public void setCcyqfy(Double ccyqfy) {
        this.ccyqfy = ccyqfy;
    }

    public Double getZje() {
        return this.zje;
    }
    
    public void setZje(Double zje) {
        this.zje = zje;
    }

    public Integer getSsxs() {
        return this.ssxs;
    }
    
    public void setSsxs(Integer ssxs) {
        this.ssxs = ssxs;
    }

    public Integer getSssysz() {
        return this.sssysz;
    }
    
    public void setSssysz(Integer sssysz) {
        this.sssysz = sssysz;
    }
	public String getSsjg() {
		return ssjg;
	}
	public void setSsjg(String ssjg) {
		this.ssjg = ssjg;
	}

	public Double getYfk() {
		return yfk;
	}

	public void setYfk(Double yfk) {
		this.yfk = yfk;
	}   
}