package com.whjbsoft.www.exam.po;

/**
 * DtxxId generated by MyEclipse - Hibernate Tools
 */

public class DtxxsId implements java.io.Serializable {

	// Fields    

	private Djxxs djxx;
	private Stgls stgl;

	// Constructors

	/** default constructor */
	public DtxxsId() {
	}

	/** full constructor */
	public DtxxsId(Djxxs djxx, Stgls stgl) {
		this.djxx = djxx;
		this.stgl = stgl;
	}

	// Property accessors

	public Djxxs getDjxx() {
		return this.djxx;
	}

	public void setDjxx(Djxxs djxx) {
		this.djxx = djxx;
	}

	public Stgls getStgl() {
		return this.stgl;
	}

	public void setStgl(Stgls stgl) {
		this.stgl = stgl;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof DtxxsId))
			return false;
		DtxxsId castOther = (DtxxsId) other;

		return ((this.getDjxx() == castOther.getDjxx()) || (this.getDjxx() != null
				&& castOther.getDjxx() != null && this.getDjxx().equals(
				castOther.getDjxx())))
				&& ((this.getStgl() == castOther.getStgl()) || (this.getStgl() != null
						&& castOther.getStgl() != null && this.getStgl()
						.equals(castOther.getStgl())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getDjxx() == null ? 0 : this.getDjxx().hashCode());
		result = 37 * result
				+ (getStgl() == null ? 0 : this.getStgl().hashCode());
		return result;
	}

}