package com.whjbsoft.www.exam.po;

import java.util.HashSet;
import java.util.Set;


/**
 * Stgl generated by MyEclipse - Hibernate Tools
 */

public class Stgls  implements java.io.Serializable {


    // Fields    

     private Integer stzj;
     private Tkgls tkgl;
     private String stmc;
     private String stlx;
     private String stnyd;
     private String xxa;
     private String xxb;
     private String xxc;
     private String xxd;
     private String xxe;
     private String xxf;
     private String zqda;
     private String ckda;
     private Set dtxxes = new HashSet(0);
     private Set sjkts = new HashSet(0);


    // Constructors

    /** default constructor */
    public Stgls() {
    }
    
    public Stgls(Integer stzj, Tkgls tkgl, String stmc, String stlx,
			String stnyd, String xxa, String xxb, String xxc, String xxd,
			String xxe, String xxf, String zqda, String ckda) {
		super();
		this.stzj = stzj;
		this.tkgl = tkgl;
		this.stmc = stmc;
		this.stlx = stlx;
		this.stnyd = stnyd;
		this.xxa = xxa;
		this.xxb = xxb;
		this.xxc = xxc;
		this.xxd = xxd;
		this.xxe = xxe;
		this.xxf = xxf;
		this.zqda = zqda;
		this.ckda = ckda;
	}


	/** full constructor */
    public Stgls(Tkgls tkgl, String stmc, String stlx, String stnyd, String xxa, String xxb, String xxc, String xxd, String xxe, String xxf, String zqda, String ckda, Set dtxxes, Set sjkts) {
        this.tkgl = tkgl;
        this.stmc = stmc;
        this.stlx = stlx;
        this.stnyd = stnyd;
        this.xxa = xxa;
        this.xxb = xxb;
        this.xxc = xxc;
        this.xxd = xxd;
        this.xxe = xxe;
        this.xxf = xxf;
        this.zqda = zqda;
        this.ckda = ckda;
        this.dtxxes = dtxxes;
        this.sjkts = sjkts;
    }

   
    // Property accessors

    public Integer getStzj() {
        return this.stzj;
    }
    
    public void setStzj(Integer stzj) {
        this.stzj = stzj;
    }

    public Tkgls getTkgl() {
        return this.tkgl;
    }
    
    public void setTkgl(Tkgls tkgl) {
        this.tkgl = tkgl;
    }

    public String getStmc() {
        return this.stmc;
    }
    
    public void setStmc(String stmc) {
        this.stmc = stmc;
    }

    public String getStlx() {
        return this.stlx;
    }
    
    public void setStlx(String stlx) {
        this.stlx = stlx;
    }

    public String getStnyd() {
        return this.stnyd;
    }
    
    public void setStnyd(String stnyd) {
        this.stnyd = stnyd;
    }

    public String getXxa() {
        return this.xxa;
    }
    
    public void setXxa(String xxa) {
        this.xxa = xxa;
    }

    public String getXxb() {
        return this.xxb;
    }
    
    public void setXxb(String xxb) {
        this.xxb = xxb;
    }

    public String getXxc() {
        return this.xxc;
    }
    
    public void setXxc(String xxc) {
        this.xxc = xxc;
    }

    public String getXxd() {
        return this.xxd;
    }
    
    public void setXxd(String xxd) {
        this.xxd = xxd;
    }

    public String getXxe() {
        return this.xxe;
    }
    
    public void setXxe(String xxe) {
        this.xxe = xxe;
    }

    public String getXxf() {
        return this.xxf;
    }
    
    public void setXxf(String xxf) {
        this.xxf = xxf;
    }

    public String getZqda() {
        return this.zqda;
    }
    
    public void setZqda(String zqda) {
        this.zqda = zqda;
    }

    public String getCkda() {
        return this.ckda;
    }
    
    public void setCkda(String ckda) {
        this.ckda = ckda;
    }

    public Set getDtxxes() {
        return this.dtxxes;
    }
    
    public void setDtxxes(Set dtxxes) {
        this.dtxxes = dtxxes;
    }

    public Set getSjkts() {
        return this.sjkts;
    }
    
    public void setSjkts(Set sjkts) {
        this.sjkts = sjkts;
    }
   








}