package com.whjbsoft.www.exam.po;

import java.util.HashSet;
import java.util.Set;


/**
 * Tkgl generated by MyEclipse - Hibernate Tools
 */

public class Tkgls  implements java.io.Serializable {


    // Fields    

     private Integer tkzj;
     private String tkmc;
     private String tklx;
     private String tkcjsj;
     private String tkcjr;
     private Set stgls = new HashSet(0);


    // Constructors

    /** default constructor */
    public Tkgls() {
    }

    
    /** full constructor */
    public Tkgls(String tkmc, String tklx, String tkcjsj, String tkcjr, Set stgls) {
        this.tkmc = tkmc;
        this.tklx = tklx;
        this.tkcjsj = tkcjsj;
        this.tkcjr = tkcjr;
        this.stgls = stgls;
    }

   
    // Property accessors

    public Integer getTkzj() {
        return this.tkzj;
    }
    
    public void setTkzj(Integer tkzj) {
        this.tkzj = tkzj;
    }

    public String getTkmc() {
        return this.tkmc;
    }
    
    public void setTkmc(String tkmc) {
        this.tkmc = tkmc;
    }

    public String getTklx() {
        return this.tklx;
    }
    
    public void setTklx(String tklx) {
        this.tklx = tklx;
    }

    public String getTkcjsj() {
        return this.tkcjsj;
    }
    
    public void setTkcjsj(String tkcjsj) {
        this.tkcjsj = tkcjsj;
    }

    public String getTkcjr() {
        return this.tkcjr;
    }
    
    public void setTkcjr(String tkcjr) {
        this.tkcjr = tkcjr;
    }

    public Set getStgls() {
        return this.stgls;
    }
    
    public void setStgls(Set stgls) {
        this.stgls = stgls;
    }
   








}