/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.whjbsoft.www.form;

import org.apache.struts.action.ActionForm;
import com.whjbsoft.www.po.Jsgl;

/** 
 * MyEclipse Struts
 * Creation date: 11-25-2009
 * 
 * XDoclet definition:
 * @struts.form name="jsglForm"
 */
public class JsglForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** vo property */
	private Jsgl vo = new Jsgl();

	/*
	 * Generated Methods
	 */

	/** 
	 * Returns the vo.
	 * @return Jsgl
	 */
	public Jsgl getVo() {
		return vo;
	}

	/** 
	 * Set the vo.
	 * @param vo The vo to set
	 */
	public void setVo(Jsgl vo) {
		this.vo = vo;
	}
}