/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.whjbsoft.www.form;

import org.apache.struts.action.ActionForm;
import com.whjbsoft.www.po.Khts;

/** 
 * MyEclipse Struts
 * Creation date: 01-12-2010
 * 
 * XDoclet definition:
 * @struts.form name="khtsForm"
 */
public class KhtsForm extends ActionForm {
	/*
	 * Generated fields
	 */
	private String fieldName;
	private String fieldValue;
	
	/** vo property */
	private Khts vo = new Khts();

	/*
	 * Generated Methods
	 */

	/** 
	 * Returns the vo.
	 * @return Khts
	 */
	public Khts getVo() {
		return vo;
	}

	/** 
	 * Set the vo.
	 * @param vo The vo to set
	 */
	public void setVo(Khts vo) {
		this.vo = vo;
	}

	public String getFieldName() {
		return fieldName;
	}

	public void setFieldName(String fieldName) {
		this.fieldName = fieldName;
	}

	public String getFieldValue() {
		return fieldValue;
	}

	public void setFieldValue(String fieldValue) {
		this.fieldValue = fieldValue;
	}
}