/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.whjbsoft.www.form;

import org.apache.struts.action.ActionForm;
import org.apache.struts.upload.FormFile;

import com.whjbsoft.www.po.Xsxx;

/** 
 * MyEclipse Struts
 * Creation date: 09-25-2009
 * 
 * XDoclet definition:
 * @struts.form name="stuForm"
 */
public class StuForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** vo property */
	private Xsxx vo = new Xsxx();
	private String fieldName;
	private String fieldValue;
	private Integer zcsl;
	private FormFile file;

	/*
	 * Generated Methods
	 */

	/**
	 * @return the zcsl
	 */
	public Integer getZcsl() {
		return zcsl;
	}

	/**
	 * @param zcsl the zcsl to set
	 */
	public void setZcsl(Integer zcsl) {
		this.zcsl = zcsl;
	}

	/** 
	 * Returns the vo.
	 * @return Xsgl
	 */
	public Xsxx getVo() {
		return vo;
	}

	/** 
	 * Set the vo.
	 * @param vo The vo to set
	 */
	public void setVo(Xsxx vo) {
		this.vo = vo;
	}

	public String getFieldName() {
		return fieldName;
	}

	public void setFieldName(String fieldName) {
		this.fieldName = fieldName;
	}

	public String getFieldValue() {
		return fieldValue;
	}

	public void setFieldValue(String fieldValue) {
		this.fieldValue = fieldValue;
	}

	public FormFile getFile() {
		return file;
	}

	public void setFile(FormFile file) {
		this.file = file;
	}
}