/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.whjbsoft.www.form;

import org.apache.struts.action.ActionForm;

import com.whjbsoft.www.po.Sysz;

/** 
 * MyEclipse Struts
 * Creation date: 07-02-2009
 * 
 * XDoclet definition:
 * @struts.form name="testSetupForm"
 */
public class TestSetupForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** s property */
	private Sysz vo = new Sysz();

	public Sysz getVo() {
		return vo;
	}

	public void setVo(Sysz vo) {
		this.vo = vo;
	}


}