/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.whjbsoft.www.form;

import org.apache.struts.action.ActionForm;
import com.whjbsoft.www.po.Ygxx;

/** 
 * MyEclipse Struts
 * Creation date: 11-27-2009
 * 
 * XDoclet definition:
 * @struts.form name="ygglForm"
 */
public class YgglForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** vo property */
	private Ygxx vo = new Ygxx();
	
	private String fieldName;
	private String fieldValue;

	/*
	 * Generated Methods
	 */

	/**
	 * @return the fieldName
	 */
	public String getFieldName() {
		return fieldName;
	}

	/**
	 * @param fieldName the fieldName to set
	 */
	public void setFieldName(String fieldName) {
		this.fieldName = fieldName;
	}

	/**
	 * @return the fieldValue
	 */
	public String getFieldValue() {
		return fieldValue;
	}

	/**
	 * @param fieldValue the fieldValue to set
	 */
	public void setFieldValue(String fieldValue) {
		this.fieldValue = fieldValue;
	}

	/** 
	 * Returns the vo.
	 * @return Ygxx
	 */
	public Ygxx getVo() {
		return vo;
	}

	/** 
	 * Set the vo.
	 * @param vo The vo to set
	 */
	public void setVo(Ygxx vo) {
		this.vo = vo;
	}
}